// This file was automatically generated by EbnfStudio; don't modify it!
#include "MpsParser.h"
using namespace Mps;

static inline bool FIRST_Mumps76(int tt) {
	switch(tt){
	case Tok_BREAK:
	case Tok_CLOSE:
	case Tok_CmdSep:
	case Tok_DO:
	case Tok_Dot:
	case Tok_ELSE:
	case Tok_FOR:
	case Tok_GOTO:
	case Tok_HALT:
	case Tok_IF:
	case Tok_JOB:
	case Tok_KILL:
	case Tok_LOCK:
	case Tok_NEW:
	case Tok_Newline:
	case Tok_OPEN:
	case Tok_QUIT:
	case Tok_READ:
	case Tok_SET:
	case Tok_USE:
	case Tok_VIEW:
	case Tok_WRITE:
	case Tok_XECUTE:
	case Tok_ZCMD:
	case Tok_ident:
		return true;
	default: return false;
	}
}

static inline bool FIRST_line(int tt) {
	switch(tt){
	case Tok_BREAK:
	case Tok_CLOSE:
	case Tok_CmdSep:
	case Tok_DO:
	case Tok_Dot:
	case Tok_ELSE:
	case Tok_FOR:
	case Tok_GOTO:
	case Tok_HALT:
	case Tok_IF:
	case Tok_JOB:
	case Tok_KILL:
	case Tok_LOCK:
	case Tok_NEW:
	case Tok_Newline:
	case Tok_OPEN:
	case Tok_QUIT:
	case Tok_READ:
	case Tok_SET:
	case Tok_USE:
	case Tok_VIEW:
	case Tok_WRITE:
	case Tok_XECUTE:
	case Tok_ZCMD:
	case Tok_ident:
		return true;
	default: return false;
	}
}

static inline bool FIRST_label(int tt) {
	return tt == Tok_ident;
}

static inline bool FIRST_params(int tt) {
	switch(tt){
	case Tok_2Dlr:
	case Tok_At:
	case Tok_Dlr:
	case Tok_Hat:
	case Tok_Lpar:
	case Tok_Minus:
	case Tok_Plus:
	case Tok_ident:
	case Tok_integer:
	case Tok_real:
	case Tok_string:
	case Tok_tick:
		return true;
	default: return false;
	}
}

static inline bool FIRST_command(int tt) {
	switch(tt){
	case Tok_BREAK:
	case Tok_CLOSE:
	case Tok_DO:
	case Tok_ELSE:
	case Tok_FOR:
	case Tok_GOTO:
	case Tok_HALT:
	case Tok_IF:
	case Tok_JOB:
	case Tok_KILL:
	case Tok_LOCK:
	case Tok_NEW:
	case Tok_OPEN:
	case Tok_QUIT:
	case Tok_READ:
	case Tok_SET:
	case Tok_USE:
	case Tok_VIEW:
	case Tok_WRITE:
	case Tok_XECUTE:
	case Tok_ZCMD:
		return true;
	default: return false;
	}
}

static inline bool FIRST_break_(int tt) {
	return tt == Tok_BREAK;
}

static inline bool FIRST_close_(int tt) {
	return tt == Tok_CLOSE;
}

static inline bool FIRST_do_(int tt) {
	return tt == Tok_DO;
}

static inline bool FIRST_else_(int tt) {
	return tt == Tok_ELSE;
}

static inline bool FIRST_for_(int tt) {
	return tt == Tok_FOR;
}

static inline bool FIRST_goto_(int tt) {
	return tt == Tok_GOTO;
}

static inline bool FIRST_halt_(int tt) {
	return tt == Tok_HALT;
}

static inline bool FIRST_if_(int tt) {
	return tt == Tok_IF;
}

static inline bool FIRST_kill_(int tt) {
	return tt == Tok_KILL;
}

static inline bool FIRST_lock_(int tt) {
	return tt == Tok_LOCK;
}

static inline bool FIRST_open_(int tt) {
	return tt == Tok_OPEN;
}

static inline bool FIRST_quit_(int tt) {
	return tt == Tok_QUIT;
}

static inline bool FIRST_read_(int tt) {
	return tt == Tok_READ;
}

static inline bool FIRST_set_(int tt) {
	return tt == Tok_SET;
}

static inline bool FIRST_use_(int tt) {
	return tt == Tok_USE;
}

static inline bool FIRST_useargs(int tt) {
	switch(tt){
	case Tok_2Dlr:
	case Tok_At:
	case Tok_Dlr:
	case Tok_Hat:
	case Tok_Lpar:
	case Tok_Minus:
	case Tok_Plus:
	case Tok_ident:
	case Tok_integer:
	case Tok_real:
	case Tok_string:
	case Tok_tick:
		return true;
	default: return false;
	}
}

static inline bool FIRST_usearg(int tt) {
	switch(tt){
	case Tok_2Dlr:
	case Tok_At:
	case Tok_Dlr:
	case Tok_Hat:
	case Tok_Lpar:
	case Tok_Minus:
	case Tok_Plus:
	case Tok_ident:
	case Tok_integer:
	case Tok_real:
	case Tok_string:
	case Tok_tick:
		return true;
	default: return false;
	}
}

static inline bool FIRST_view_(int tt) {
	return tt == Tok_VIEW;
}

static inline bool FIRST_write_(int tt) {
	return tt == Tok_WRITE;
}

static inline bool FIRST_xecute_(int tt) {
	return tt == Tok_XECUTE;
}

static inline bool FIRST_new_(int tt) {
	return tt == Tok_NEW;
}

static inline bool FIRST_job_(int tt) {
	return tt == Tok_JOB;
}

static inline bool FIRST_zcmd_(int tt) {
	return tt == Tok_ZCMD;
}

static inline bool FIRST_postcond(int tt) {
	return tt == Tok_Colon;
}

static inline bool FIRST_doargs(int tt) {
	return tt == Tok_At || tt == Tok_Hat || tt == Tok_ident || tt == Tok_integer;
}

static inline bool FIRST_doarg(int tt) {
	return tt == Tok_At || tt == Tok_Hat || tt == Tok_ident || tt == Tok_integer;
}

static inline bool FIRST_gotoargs(int tt) {
	return tt == Tok_At || tt == Tok_Hat || tt == Tok_ident || tt == Tok_integer;
}

static inline bool FIRST_gotoarg(int tt) {
	return tt == Tok_At || tt == Tok_Hat || tt == Tok_ident || tt == Tok_integer;
}

static inline bool FIRST_forargs(int tt) {
	return tt == Tok_At || tt == Tok_ident;
}

static inline bool FIRST_forarg(int tt) {
	switch(tt){
	case Tok_2Dlr:
	case Tok_At:
	case Tok_Dlr:
	case Tok_Hat:
	case Tok_Lpar:
	case Tok_Minus:
	case Tok_Plus:
	case Tok_ident:
	case Tok_integer:
	case Tok_real:
	case Tok_string:
	case Tok_tick:
		return true;
	default: return false;
	}
}

static inline bool FIRST_killargs(int tt) {
	return tt == Tok_At || tt == Tok_Dlr || tt == Tok_Hat || tt == Tok_Lpar || tt == Tok_ident;
}

static inline bool FIRST_killarg(int tt) {
	return tt == Tok_At || tt == Tok_Dlr || tt == Tok_Hat || tt == Tok_Lpar || tt == Tok_ident;
}

static inline bool FIRST_lockargs(int tt) {
	return tt == Tok_At || tt == Tok_Hat || tt == Tok_Lpar || tt == Tok_ident;
}

static inline bool FIRST_lockarg(int tt) {
	return tt == Tok_At || tt == Tok_Hat || tt == Tok_Lpar || tt == Tok_ident;
}

static inline bool FIRST_nref(int tt) {
	return tt == Tok_At || tt == Tok_Hat || tt == Tok_Lpar || tt == Tok_ident;
}

static inline bool FIRST_openargs(int tt) {
	switch(tt){
	case Tok_2Dlr:
	case Tok_At:
	case Tok_Dlr:
	case Tok_Hat:
	case Tok_Lpar:
	case Tok_Minus:
	case Tok_Plus:
	case Tok_ident:
	case Tok_integer:
	case Tok_real:
	case Tok_string:
	case Tok_tick:
		return true;
	default: return false;
	}
}

static inline bool FIRST_openarg(int tt) {
	switch(tt){
	case Tok_2Dlr:
	case Tok_At:
	case Tok_Dlr:
	case Tok_Hat:
	case Tok_Lpar:
	case Tok_Minus:
	case Tok_Plus:
	case Tok_ident:
	case Tok_integer:
	case Tok_real:
	case Tok_string:
	case Tok_tick:
		return true;
	default: return false;
	}
}

static inline bool FIRST_openparams(int tt) {
	return tt == Tok_Colon;
}

static inline bool FIRST_openparam(int tt) {
	switch(tt){
	case Tok_2Dlr:
	case Tok_At:
	case Tok_Dlr:
	case Tok_Hat:
	case Tok_Lpar:
	case Tok_Minus:
	case Tok_Plus:
	case Tok_ident:
	case Tok_integer:
	case Tok_real:
	case Tok_string:
	case Tok_tick:
		return true;
	default: return false;
	}
}

static inline bool FIRST_readargs(int tt) {
	switch(tt){
	case Tok_At:
	case Tok_Bang:
	case Tok_Hash:
	case Tok_Hat:
	case Tok_Qmark:
	case Tok_Star:
	case Tok_ident:
	case Tok_string:
		return true;
	default: return false;
	}
}

static inline bool FIRST_readarg(int tt) {
	switch(tt){
	case Tok_At:
	case Tok_Bang:
	case Tok_Hash:
	case Tok_Hat:
	case Tok_Qmark:
	case Tok_Star:
	case Tok_ident:
	case Tok_string:
		return true;
	default: return false;
	}
}

static inline bool FIRST_readfmt(int tt) {
	return tt == Tok_Bang || tt == Tok_Hash || tt == Tok_Qmark || tt == Tok_Star;
}

static inline bool FIRST_readvar(int tt) {
	return tt == Tok_At || tt == Tok_Hat || tt == Tok_ident;
}

static inline bool FIRST_setargs(int tt) {
	switch(tt){
	case Tok_At:
	case Tok_Dlr:
	case Tok_Eq:
	case Tok_Hat:
	case Tok_Lpar:
	case Tok_ident:
		return true;
	default: return false;
	}
}

static inline bool FIRST_setarg(int tt) {
	switch(tt){
	case Tok_At:
	case Tok_Dlr:
	case Tok_Eq:
	case Tok_Hat:
	case Tok_Lpar:
	case Tok_ident:
		return true;
	default: return false;
	}
}

static inline bool FIRST_setdest(int tt) {
	return tt == Tok_At || tt == Tok_Dlr || tt == Tok_Hat || tt == Tok_Lpar || tt == Tok_ident;
}

static inline bool FIRST_writeargs(int tt) {
	switch(tt){
	case Tok_2Dlr:
	case Tok_At:
	case Tok_Bang:
	case Tok_Dlr:
	case Tok_Hash:
	case Tok_Hat:
	case Tok_Lpar:
	case Tok_Minus:
	case Tok_Plus:
	case Tok_Qmark:
	case Tok_Star:
	case Tok_ident:
	case Tok_integer:
	case Tok_real:
	case Tok_string:
	case Tok_tick:
		return true;
	default: return false;
	}
}

static inline bool FIRST_writearg(int tt) {
	switch(tt){
	case Tok_2Dlr:
	case Tok_At:
	case Tok_Bang:
	case Tok_Dlr:
	case Tok_Hash:
	case Tok_Hat:
	case Tok_Lpar:
	case Tok_Minus:
	case Tok_Plus:
	case Tok_Qmark:
	case Tok_Star:
	case Tok_ident:
	case Tok_integer:
	case Tok_real:
	case Tok_string:
	case Tok_tick:
		return true;
	default: return false;
	}
}

static inline bool FIRST_xecuteargs(int tt) {
	switch(tt){
	case Tok_2Dlr:
	case Tok_At:
	case Tok_Dlr:
	case Tok_Hat:
	case Tok_Lpar:
	case Tok_Minus:
	case Tok_Plus:
	case Tok_ident:
	case Tok_integer:
	case Tok_real:
	case Tok_string:
	case Tok_tick:
		return true;
	default: return false;
	}
}

static inline bool FIRST_xecutearg(int tt) {
	switch(tt){
	case Tok_2Dlr:
	case Tok_At:
	case Tok_Dlr:
	case Tok_Hat:
	case Tok_Lpar:
	case Tok_Minus:
	case Tok_Plus:
	case Tok_ident:
	case Tok_integer:
	case Tok_real:
	case Tok_string:
	case Tok_tick:
		return true;
	default: return false;
	}
}

static inline bool FIRST_newargs(int tt) {
	return tt == Tok_Lpar || tt == Tok_ident;
}

static inline bool FIRST_newarg(int tt) {
	return tt == Tok_Lpar || tt == Tok_ident;
}

static inline bool FIRST_jobargs(int tt) {
	return tt == Tok_At || tt == Tok_Hat || tt == Tok_ident || tt == Tok_integer;
}

static inline bool FIRST_viewargs(int tt) {
	switch(tt){
	case Tok_2Dlr:
	case Tok_At:
	case Tok_Colon:
	case Tok_Comma:
	case Tok_Dlr:
	case Tok_Hat:
	case Tok_Lpar:
	case Tok_Minus:
	case Tok_Plus:
	case Tok_ident:
	case Tok_integer:
	case Tok_real:
	case Tok_string:
	case Tok_tick:
		return true;
	default: return false;
	}
}

static inline bool FIRST_viewgroup(int tt) {
	switch(tt){
	case Tok_2Dlr:
	case Tok_At:
	case Tok_Colon:
	case Tok_Dlr:
	case Tok_Hat:
	case Tok_Lpar:
	case Tok_Minus:
	case Tok_Plus:
	case Tok_ident:
	case Tok_integer:
	case Tok_real:
	case Tok_string:
	case Tok_tick:
		return true;
	default: return false;
	}
}

static inline bool FIRST_zargs(int tt) {
	switch(tt){
	case Tok_2Dlr:
	case Tok_At:
	case Tok_Dlr:
	case Tok_Hat:
	case Tok_Lpar:
	case Tok_Minus:
	case Tok_Plus:
	case Tok_ident:
	case Tok_integer:
	case Tok_real:
	case Tok_string:
	case Tok_tick:
		return true;
	default: return false;
	}
}

static inline bool FIRST_entryref(int tt) {
	return tt == Tok_At || tt == Tok_Hat || tt == Tok_ident || tt == Tok_integer;
}

static inline bool FIRST_actuallist(int tt) {
	switch(tt){
	case Tok_2Dlr:
	case Tok_At:
	case Tok_Dlr:
	case Tok_Dot:
	case Tok_Hat:
	case Tok_Lpar:
	case Tok_Minus:
	case Tok_Plus:
	case Tok_ident:
	case Tok_integer:
	case Tok_real:
	case Tok_string:
	case Tok_tick:
		return true;
	default: return false;
	}
}

static inline bool FIRST_label_ref(int tt) {
	return tt == Tok_ident || tt == Tok_integer;
}

static inline bool FIRST_routineref(int tt) {
	return tt == Tok_At || tt == Tok_ident;
}

static inline bool FIRST_exprlist(int tt) {
	switch(tt){
	case Tok_2Dlr:
	case Tok_At:
	case Tok_Dlr:
	case Tok_Dot:
	case Tok_Hat:
	case Tok_Lpar:
	case Tok_Minus:
	case Tok_Plus:
	case Tok_ident:
	case Tok_integer:
	case Tok_real:
	case Tok_string:
	case Tok_tick:
		return true;
	default: return false;
	}
}

static inline bool FIRST_expr(int tt) {
	switch(tt){
	case Tok_2Dlr:
	case Tok_At:
	case Tok_Dlr:
	case Tok_Hat:
	case Tok_Lpar:
	case Tok_Minus:
	case Tok_Plus:
	case Tok_ident:
	case Tok_integer:
	case Tok_real:
	case Tok_string:
	case Tok_tick:
		return true;
	default: return false;
	}
}

static inline bool FIRST_pattern(int tt) {
	switch(tt){
	case Tok_At:
	case Tok_Dot:
	case Tok_Lpar:
	case Tok_ident:
	case Tok_integer:
	case Tok_real:
	case Tok_string:
		return true;
	default: return false;
	}
}

static inline bool FIRST_patAtom(int tt) {
	switch(tt){
	case Tok_At:
	case Tok_Dot:
	case Tok_Lpar:
	case Tok_ident:
	case Tok_integer:
	case Tok_real:
	case Tok_string:
		return true;
	default: return false;
	}
}

static inline bool FIRST_patAlt(int tt) {
	switch(tt){
	case Tok_At:
	case Tok_Dot:
	case Tok_Lpar:
	case Tok_ident:
	case Tok_integer:
	case Tok_real:
	case Tok_string:
		return true;
	default: return false;
	}
}

static inline bool FIRST_expratom(int tt) {
	switch(tt){
	case Tok_2Dlr:
	case Tok_At:
	case Tok_Dlr:
	case Tok_Hat:
	case Tok_Lpar:
	case Tok_Minus:
	case Tok_Plus:
	case Tok_ident:
	case Tok_integer:
	case Tok_real:
	case Tok_string:
	case Tok_tick:
		return true;
	default: return false;
	}
}

static inline bool FIRST_numlit(int tt) {
	return tt == Tok_integer || tt == Tok_real;
}

static inline bool FIRST_gvntail(int tt) {
	return tt == Tok_At || tt == Tok_Lpar || tt == Tok_ident;
}

static inline bool FIRST_dollaritem(int tt) {
	return tt == Tok_2Dlr || tt == Tok_Dlr;
}

static inline bool FIRST_funcargs(int tt) {
	switch(tt){
	case Tok_2Dlr:
	case Tok_At:
	case Tok_Dlr:
	case Tok_Hat:
	case Tok_Lpar:
	case Tok_Minus:
	case Tok_Plus:
	case Tok_ident:
	case Tok_integer:
	case Tok_real:
	case Tok_string:
	case Tok_tick:
		return true;
	default: return false;
	}
}

static inline bool FIRST_funcarg(int tt) {
	switch(tt){
	case Tok_2Dlr:
	case Tok_At:
	case Tok_Dlr:
	case Tok_Hat:
	case Tok_Lpar:
	case Tok_Minus:
	case Tok_Plus:
	case Tok_ident:
	case Tok_integer:
	case Tok_real:
	case Tok_string:
	case Tok_tick:
		return true;
	default: return false;
	}
}

static inline bool FIRST_unaryop(int tt) {
	return tt == Tok_Minus || tt == Tok_Plus || tt == Tok_tick;
}

static inline bool FIRST_binop(int tt) {
	switch(tt){
	case Tok_5f:
	case Tok_Amp:
	case Tok_Bang:
	case Tok_Eq:
	case Tok_Gt:
	case Tok_Hash:
	case Tok_Lbrack:
	case Tok_Lt:
	case Tok_Minus:
	case Tok_Plus:
	case Tok_Rbrack:
	case Tok_Slash:
	case Tok_Star:
	case Tok_bslash:
		return true;
	default: return false;
	}
}

static inline bool FIRST_exprCont(int tt) {
	switch(tt){
	case Tok_5f:
	case Tok_Amp:
	case Tok_Bang:
	case Tok_Eq:
	case Tok_Gt:
	case Tok_Hash:
	case Tok_Lbrack:
	case Tok_Lt:
	case Tok_Minus:
	case Tok_Plus:
	case Tok_Qmark:
	case Tok_Rbrack:
	case Tok_Slash:
	case Tok_Star:
	case Tok_bslash:
		return true;
	default: return false;
	}
}

static inline bool FIRST_glvn(int tt) {
	return tt == Tok_At || tt == Tok_Hat || tt == Tok_ident;
}

static inline bool FIRST_lvar(int tt) {
	return tt == Tok_At || tt == Tok_ident;
}

void Parser::RunParser() {
	errors.clear();
	next();
	Mumps76();
}

void Parser::next() {
	cur = la;
	la = scanner->next();
	while( la.d_type == Tok_Invalid ) {
		errors << Error(la.d_val, la.d_lineNr, la.d_colNr, la.d_sourcePath);
		la = scanner->next();
	}
}

Token Parser::peek(int off) {
	if( off == 1 )
		return la;
	else if( off == 0 )
		return cur;
	else
		return scanner->peek(off-1);
}

void Parser::invalid(const char* what) {
	errors << Error(QString("invalid %1").arg(what),la.d_lineNr, la.d_colNr, la.d_sourcePath);
}

bool Parser::expect(int tt, bool pkw, const char* where) {
	if( la.d_type == tt) { next(); return true; }
	else { errors << Error(QString("'%1' expected in %2").arg(tokenTypeString(tt)).arg(where),la.d_lineNr, la.d_colNr, la.d_sourcePath); return false; }
}

static inline void dummy() {}

void Parser::Mumps76() {
	while( FIRST_line(la.d_type) ) {
		line();
	}
}

void Parser::line() {
	if( FIRST_label(la.d_type) ) {
		label();
	}
	while( la.d_type == Tok_Dot ) {
		expect(Tok_Dot, false, "line");
	}
	while( la.d_type == Tok_CmdSep || FIRST_command(la.d_type) ) {
		if( la.d_type == Tok_CmdSep ) {
			expect(Tok_CmdSep, false, "line");
		}
		command();
	}
	expect(Tok_Newline, false, "line");
}

void Parser::label() {
	expect(Tok_ident, false, "label");
	if( la.d_type == Tok_Lpar ) {
		expect(Tok_Lpar, false, "label");
		params();
		expect(Tok_Rpar, false, "label");
	}
}

void Parser::params() {
	if( FIRST_expr(la.d_type) ) {
		expr();
		while( la.d_type == Tok_Comma ) {
			expect(Tok_Comma, false, "params");
			expr();
		}
	}
}

void Parser::command() {
	if( FIRST_break_(la.d_type) ) {
		break_();
	} else if( FIRST_close_(la.d_type) ) {
		close_();
	} else if( FIRST_do_(la.d_type) ) {
		do_();
	} else if( FIRST_else_(la.d_type) ) {
		else_();
	} else if( FIRST_for_(la.d_type) ) {
		for_();
	} else if( FIRST_goto_(la.d_type) ) {
		goto_();
	} else if( FIRST_halt_(la.d_type) ) {
		halt_();
	} else if( FIRST_if_(la.d_type) ) {
		if_();
	} else if( FIRST_kill_(la.d_type) ) {
		kill_();
	} else if( FIRST_lock_(la.d_type) ) {
		lock_();
	} else if( FIRST_open_(la.d_type) ) {
		open_();
	} else if( FIRST_quit_(la.d_type) ) {
		quit_();
	} else if( FIRST_read_(la.d_type) ) {
		read_();
	} else if( FIRST_set_(la.d_type) ) {
		set_();
	} else if( FIRST_use_(la.d_type) ) {
		use_();
	} else if( FIRST_view_(la.d_type) ) {
		view_();
	} else if( FIRST_write_(la.d_type) ) {
		write_();
	} else if( FIRST_xecute_(la.d_type) ) {
		xecute_();
	} else if( FIRST_new_(la.d_type) ) {
		new_();
	} else if( FIRST_job_(la.d_type) ) {
		job_();
	} else if( FIRST_zcmd_(la.d_type) ) {
		zcmd_();
	} else
		invalid("command");
}

void Parser::break_() {
	expect(Tok_BREAK, false, "break_");
	if( FIRST_postcond(la.d_type) ) {
		postcond();
	}
	if( la.d_type == Tok_CmdSep ) {
		expect(Tok_CmdSep, false, "break_");
	}
	if( FIRST_exprlist(la.d_type) ) {
		exprlist();
	}
}

void Parser::close_() {
	expect(Tok_CLOSE, false, "close_");
	if( FIRST_postcond(la.d_type) ) {
		postcond();
	}
	if( la.d_type == Tok_CmdSep ) {
		expect(Tok_CmdSep, false, "close_");
	}
	openargs();
}

void Parser::do_() {
	expect(Tok_DO, false, "do_");
	if( FIRST_postcond(la.d_type) ) {
		postcond();
	}
	if( la.d_type == Tok_CmdSep ) {
		expect(Tok_CmdSep, false, "do_");
	}
	if( FIRST_doargs(la.d_type) ) {
		doargs();
	}
}

void Parser::else_() {
	expect(Tok_ELSE, false, "else_");
}

void Parser::for_() {
	expect(Tok_FOR, false, "for_");
	if( FIRST_postcond(la.d_type) ) {
		postcond();
	}
	if( la.d_type == Tok_CmdSep ) {
		expect(Tok_CmdSep, false, "for_");
	}
	if( FIRST_forargs(la.d_type) ) {
		forargs();
	}
}

void Parser::goto_() {
	expect(Tok_GOTO, false, "goto_");
	if( FIRST_postcond(la.d_type) ) {
		postcond();
	}
	if( la.d_type == Tok_CmdSep ) {
		expect(Tok_CmdSep, false, "goto_");
	}
	gotoargs();
}

void Parser::halt_() {
	expect(Tok_HALT, false, "halt_");
	if( FIRST_postcond(la.d_type) ) {
		postcond();
	}
	if( la.d_type == Tok_CmdSep ) {
		expect(Tok_CmdSep, false, "halt_");
	}
	if( FIRST_exprlist(la.d_type) ) {
		exprlist();
	}
}

void Parser::if_() {
	expect(Tok_IF, false, "if_");
	if( FIRST_postcond(la.d_type) ) {
		postcond();
	}
	if( la.d_type == Tok_CmdSep ) {
		expect(Tok_CmdSep, false, "if_");
	}
	if( FIRST_exprlist(la.d_type) ) {
		exprlist();
	}
}

void Parser::kill_() {
	expect(Tok_KILL, false, "kill_");
	if( FIRST_postcond(la.d_type) ) {
		postcond();
	}
	if( la.d_type == Tok_CmdSep ) {
		expect(Tok_CmdSep, false, "kill_");
	}
	if( FIRST_killargs(la.d_type) ) {
		killargs();
	}
}

void Parser::lock_() {
	expect(Tok_LOCK, false, "lock_");
	if( FIRST_postcond(la.d_type) ) {
		postcond();
	}
	if( la.d_type == Tok_CmdSep ) {
		expect(Tok_CmdSep, false, "lock_");
	}
	if( FIRST_lockargs(la.d_type) ) {
		lockargs();
	}
}

void Parser::open_() {
	expect(Tok_OPEN, false, "open_");
	if( FIRST_postcond(la.d_type) ) {
		postcond();
	}
	if( la.d_type == Tok_CmdSep ) {
		expect(Tok_CmdSep, false, "open_");
	}
	openargs();
}

void Parser::quit_() {
	expect(Tok_QUIT, false, "quit_");
	if( FIRST_postcond(la.d_type) ) {
		postcond();
	}
	if( la.d_type == Tok_CmdSep ) {
		expect(Tok_CmdSep, false, "quit_");
	}
	if( FIRST_expr(la.d_type) ) {
		expr();
	}
}

void Parser::read_() {
	expect(Tok_READ, false, "read_");
	if( FIRST_postcond(la.d_type) ) {
		postcond();
	}
	if( la.d_type == Tok_CmdSep ) {
		expect(Tok_CmdSep, false, "read_");
	}
	readargs();
}

void Parser::set_() {
	expect(Tok_SET, false, "set_");
	if( FIRST_postcond(la.d_type) ) {
		postcond();
	}
	if( la.d_type == Tok_CmdSep ) {
		expect(Tok_CmdSep, false, "set_");
	}
	setargs();
}

void Parser::use_() {
	expect(Tok_USE, false, "use_");
	if( FIRST_postcond(la.d_type) ) {
		postcond();
	}
	if( la.d_type == Tok_CmdSep ) {
		expect(Tok_CmdSep, false, "use_");
	}
	if( FIRST_useargs(la.d_type) ) {
		useargs();
	}
}

void Parser::useargs() {
	usearg();
	while( la.d_type == Tok_Comma ) {
		expect(Tok_Comma, false, "useargs");
		usearg();
	}
}

void Parser::usearg() {
	expr();
	if( FIRST_openparams(la.d_type) ) {
		openparams();
	}
}

void Parser::view_() {
	expect(Tok_VIEW, false, "view_");
	if( FIRST_postcond(la.d_type) ) {
		postcond();
	}
	if( la.d_type == Tok_CmdSep ) {
		expect(Tok_CmdSep, false, "view_");
	}
	if( FIRST_viewargs(la.d_type) ) {
		viewargs();
	}
}

void Parser::write_() {
	expect(Tok_WRITE, false, "write_");
	if( FIRST_postcond(la.d_type) ) {
		postcond();
	}
	if( la.d_type == Tok_CmdSep ) {
		expect(Tok_CmdSep, false, "write_");
	}
	if( FIRST_writeargs(la.d_type) ) {
		writeargs();
	}
}

void Parser::xecute_() {
	expect(Tok_XECUTE, false, "xecute_");
	if( FIRST_postcond(la.d_type) ) {
		postcond();
	}
	if( la.d_type == Tok_CmdSep ) {
		expect(Tok_CmdSep, false, "xecute_");
	}
	xecuteargs();
}

void Parser::new_() {
	expect(Tok_NEW, false, "new_");
	if( FIRST_postcond(la.d_type) ) {
		postcond();
	}
	if( la.d_type == Tok_CmdSep ) {
		expect(Tok_CmdSep, false, "new_");
	}
	if( FIRST_newargs(la.d_type) ) {
		newargs();
	}
}

void Parser::job_() {
	expect(Tok_JOB, false, "job_");
	if( FIRST_postcond(la.d_type) ) {
		postcond();
	}
	if( la.d_type == Tok_CmdSep ) {
		expect(Tok_CmdSep, false, "job_");
	}
	jobargs();
}

void Parser::zcmd_() {
	expect(Tok_ZCMD, false, "zcmd_");
	if( FIRST_postcond(la.d_type) ) {
		postcond();
	}
	if( la.d_type == Tok_CmdSep ) {
		expect(Tok_CmdSep, false, "zcmd_");
	}
	if( FIRST_zargs(la.d_type) ) {
		zargs();
	}
}

void Parser::postcond() {
	expect(Tok_Colon, false, "postcond");
	expr();
}

void Parser::doargs() {
	doarg();
	while( la.d_type == Tok_Comma ) {
		expect(Tok_Comma, false, "doargs");
		doarg();
	}
}

void Parser::doarg() {
	entryref();
	if( FIRST_postcond(la.d_type) ) {
		postcond();
	}
}

void Parser::gotoargs() {
	gotoarg();
	while( la.d_type == Tok_Comma ) {
		expect(Tok_Comma, false, "gotoargs");
		gotoarg();
	}
}

void Parser::gotoarg() {
	entryref();
	if( FIRST_postcond(la.d_type) ) {
		postcond();
	}
}

void Parser::forargs() {
	lvar();
	expect(Tok_Eq, false, "forargs");
	forarg();
	while( la.d_type == Tok_Comma ) {
		expect(Tok_Comma, false, "forargs");
		forarg();
	}
}

void Parser::forarg() {
	expr();
	if( la.d_type == Tok_Colon ) {
		expect(Tok_Colon, false, "forarg");
		expr();
		if( la.d_type == Tok_Colon ) {
			expect(Tok_Colon, false, "forarg");
			expr();
		}
	}
}

void Parser::killargs() {
	killarg();
	while( la.d_type == Tok_Comma ) {
		expect(Tok_Comma, false, "killargs");
		killarg();
	}
}

void Parser::killarg() {
	if( FIRST_glvn(la.d_type) ) {
		glvn();
	} else if( la.d_type == Tok_Dlr ) {
		expect(Tok_Dlr, false, "killarg");
		expect(Tok_ident, false, "killarg");
	} else if( la.d_type == Tok_Lpar ) {
		expect(Tok_Lpar, false, "killarg");
		glvn();
		while( la.d_type == Tok_Comma ) {
			expect(Tok_Comma, false, "killarg");
			glvn();
		}
		expect(Tok_Rpar, false, "killarg");
	} else
		invalid("killarg");
}

void Parser::lockargs() {
	lockarg();
	while( la.d_type == Tok_Comma ) {
		expect(Tok_Comma, false, "lockargs");
		lockarg();
	}
}

void Parser::lockarg() {
	nref();
	if( la.d_type == Tok_Colon ) {
		expect(Tok_Colon, false, "lockarg");
		expr();
	}
}

void Parser::nref() {
	if( FIRST_glvn(la.d_type) ) {
		glvn();
	} else if( la.d_type == Tok_Lpar ) {
		expect(Tok_Lpar, false, "nref");
		glvn();
		while( la.d_type == Tok_Comma ) {
			expect(Tok_Comma, false, "nref");
			glvn();
		}
		expect(Tok_Rpar, false, "nref");
	} else
		invalid("nref");
}

void Parser::openargs() {
	openarg();
	while( la.d_type == Tok_Comma ) {
		expect(Tok_Comma, false, "openargs");
		openarg();
	}
}

void Parser::openarg() {
	expr();
	if( FIRST_openparams(la.d_type) ) {
		openparams();
	}
}

void Parser::openparams() {
	expect(Tok_Colon, false, "openparams");
	openparam();
	while( la.d_type == Tok_Colon ) {
		expect(Tok_Colon, false, "openparams");
		openparam();
	}
}

void Parser::openparam() {
	if( ( peek(1).d_type == Tok_Lpar )  || FIRST_expr(la.d_type) ) {
		if( ( peek(1).d_type == Tok_Lpar )  ) {
			expect(Tok_Lpar, false, "openparam");
			openparam();
			while( la.d_type == Tok_Colon ) {
				expect(Tok_Colon, false, "openparam");
				openparam();
			}
			expect(Tok_Rpar, false, "openparam");
		} else if( FIRST_expr(la.d_type) ) {
			expr();
		} else
			invalid("openparam");
	}
}

void Parser::readargs() {
	readarg();
	while( la.d_type == Tok_Comma || FIRST_readarg(la.d_type) ) {
		if( la.d_type == Tok_Comma ) {
			expect(Tok_Comma, false, "readargs");
		}
		readarg();
	}
}

void Parser::readarg() {
	if( FIRST_readfmt(la.d_type) ) {
		readfmt();
	} else if( la.d_type == Tok_string ) {
		expect(Tok_string, false, "readarg");
	} else if( FIRST_readvar(la.d_type) ) {
		readvar();
	} else
		invalid("readarg");
}

void Parser::readfmt() {
	if( la.d_type == Tok_Bang ) {
		expect(Tok_Bang, false, "readfmt");
	} else if( la.d_type == Tok_Hash ) {
		expect(Tok_Hash, false, "readfmt");
	} else if( la.d_type == Tok_Qmark ) {
		expect(Tok_Qmark, false, "readfmt");
		expr();
	} else if( la.d_type == Tok_Star ) {
		expect(Tok_Star, false, "readfmt");
		glvn();
		if( la.d_type == Tok_Colon ) {
			expect(Tok_Colon, false, "readfmt");
			expr();
		}
	} else
		invalid("readfmt");
}

void Parser::readvar() {
	glvn();
	if( la.d_type == Tok_Hash ) {
		expect(Tok_Hash, false, "readvar");
		expr();
	}
	if( la.d_type == Tok_Colon ) {
		expect(Tok_Colon, false, "readvar");
		expr();
	}
}

void Parser::setargs() {
	setarg();
	while( la.d_type == Tok_Comma ) {
		expect(Tok_Comma, false, "setargs");
		setarg();
	}
}

void Parser::setarg() {
	if( FIRST_setdest(la.d_type) ) {
		setdest();
		if( la.d_type == Tok_Eq ) {
			expect(Tok_Eq, false, "setarg");
			expr();
		}
	} else if( la.d_type == Tok_Eq ) {
		expect(Tok_Eq, false, "setarg");
	} else
		invalid("setarg");
}

void Parser::setdest() {
	if( FIRST_glvn(la.d_type) ) {
		glvn();
	} else if( la.d_type == Tok_Dlr ) {
		expect(Tok_Dlr, false, "setdest");
		expect(Tok_ident, false, "setdest");
		if( la.d_type == Tok_Lpar ) {
			expect(Tok_Lpar, false, "setdest");
			exprlist();
			expect(Tok_Rpar, false, "setdest");
		}
	} else if( la.d_type == Tok_Lpar ) {
		expect(Tok_Lpar, false, "setdest");
		setdest();
		while( la.d_type == Tok_Comma ) {
			expect(Tok_Comma, false, "setdest");
			setdest();
		}
		expect(Tok_Rpar, false, "setdest");
	} else
		invalid("setdest");
}

void Parser::writeargs() {
	writearg();
	while( la.d_type == Tok_Comma || FIRST_writearg(la.d_type) ) {
		if( la.d_type == Tok_Comma ) {
			expect(Tok_Comma, false, "writeargs");
		}
		writearg();
	}
}

void Parser::writearg() {
	if( la.d_type == Tok_Bang ) {
		expect(Tok_Bang, false, "writearg");
	} else if( la.d_type == Tok_Hash ) {
		expect(Tok_Hash, false, "writearg");
	} else if( la.d_type == Tok_Qmark ) {
		expect(Tok_Qmark, false, "writearg");
		expr();
	} else if( la.d_type == Tok_Star ) {
		expect(Tok_Star, false, "writearg");
		expr();
	} else if( FIRST_expr(la.d_type) ) {
		expr();
	} else
		invalid("writearg");
}

void Parser::xecuteargs() {
	xecutearg();
	while( la.d_type == Tok_Comma ) {
		expect(Tok_Comma, false, "xecuteargs");
		xecutearg();
	}
}

void Parser::xecutearg() {
	expr();
	if( FIRST_postcond(la.d_type) ) {
		postcond();
	}
}

void Parser::newargs() {
	newarg();
	while( la.d_type == Tok_Comma ) {
		expect(Tok_Comma, false, "newargs");
		newarg();
	}
}

void Parser::newarg() {
	if( la.d_type == Tok_ident ) {
		expect(Tok_ident, false, "newarg");
	} else if( la.d_type == Tok_Lpar ) {
		expect(Tok_Lpar, false, "newarg");
		expect(Tok_ident, false, "newarg");
		while( la.d_type == Tok_Comma ) {
			expect(Tok_Comma, false, "newarg");
			expect(Tok_ident, false, "newarg");
		}
		expect(Tok_Rpar, false, "newarg");
	} else
		invalid("newarg");
}

void Parser::jobargs() {
	entryref();
	if( la.d_type == Tok_Colon ) {
		expect(Tok_Colon, false, "jobargs");
		expr();
		while( la.d_type == Tok_Colon ) {
			expect(Tok_Colon, false, "jobargs");
			expr();
		}
	}
}

void Parser::viewargs() {
	viewgroup();
	while( la.d_type == Tok_Comma ) {
		expect(Tok_Comma, false, "viewargs");
		viewgroup();
	}
}

void Parser::viewgroup() {
	if( FIRST_expr(la.d_type) ) {
		expr();
	}
	while( la.d_type == Tok_Colon ) {
		expect(Tok_Colon, false, "viewgroup");
		if( FIRST_expr(la.d_type) ) {
			expr();
		}
	}
}

void Parser::zargs() {
	expr();
	if( la.d_type == Tok_Hat ) {
		expect(Tok_Hat, false, "zargs");
		routineref();
	}
	if( FIRST_openparams(la.d_type) ) {
		openparams();
	}
	while( la.d_type == Tok_Comma ) {
		expect(Tok_Comma, false, "zargs");
		expr();
		if( la.d_type == Tok_Hat ) {
			expect(Tok_Hat, false, "zargs");
			routineref();
		}
		if( FIRST_openparams(la.d_type) ) {
			openparams();
		}
	}
}

void Parser::entryref() {
	if( FIRST_label_ref(la.d_type) ) {
		label_ref();
		if( la.d_type == Tok_Plus ) {
			expect(Tok_Plus, false, "entryref");
			expr();
		}
		if( la.d_type == Tok_Hat ) {
			expect(Tok_Hat, false, "entryref");
			routineref();
		}
		if( la.d_type == Tok_Lpar ) {
			expect(Tok_Lpar, false, "entryref");
			if( FIRST_actuallist(la.d_type) ) {
				actuallist();
			}
			expect(Tok_Rpar, false, "entryref");
		}
	} else if( la.d_type == Tok_Hat ) {
		expect(Tok_Hat, false, "entryref");
		routineref();
		if( la.d_type == Tok_Lpar ) {
			expect(Tok_Lpar, false, "entryref");
			if( FIRST_actuallist(la.d_type) ) {
				actuallist();
			}
			expect(Tok_Rpar, false, "entryref");
		}
	} else if( la.d_type == Tok_At ) {
		expect(Tok_At, false, "entryref");
		expratom();
		if( la.d_type == Tok_Plus ) {
			expect(Tok_Plus, false, "entryref");
			expr();
		}
		if( la.d_type == Tok_Hat ) {
			expect(Tok_Hat, false, "entryref");
			routineref();
		}
		if( la.d_type == Tok_Lpar ) {
			expect(Tok_Lpar, false, "entryref");
			if( FIRST_actuallist(la.d_type) ) {
				actuallist();
			}
			expect(Tok_Rpar, false, "entryref");
		}
	} else
		invalid("entryref");
}

void Parser::actuallist() {
	if( la.d_type == Tok_Dot ) {
		expect(Tok_Dot, false, "actuallist");
	}
	expr();
	while( la.d_type == Tok_Comma ) {
		expect(Tok_Comma, false, "actuallist");
		if( la.d_type == Tok_Dot ) {
			expect(Tok_Dot, false, "actuallist");
		}
		expr();
	}
}

void Parser::label_ref() {
	if( la.d_type == Tok_ident ) {
		expect(Tok_ident, false, "label_ref");
	} else if( la.d_type == Tok_integer ) {
		expect(Tok_integer, false, "label_ref");
	} else
		invalid("label_ref");
}

void Parser::routineref() {
	if( la.d_type == Tok_ident ) {
		expect(Tok_ident, false, "routineref");
	} else if( la.d_type == Tok_At ) {
		expect(Tok_At, false, "routineref");
		expratom();
	} else
		invalid("routineref");
}

void Parser::exprlist() {
	if( la.d_type == Tok_Dot ) {
		expect(Tok_Dot, false, "exprlist");
	}
	expr();
	while( la.d_type == Tok_Comma ) {
		expect(Tok_Comma, false, "exprlist");
		if( la.d_type == Tok_Dot ) {
			expect(Tok_Dot, false, "exprlist");
		}
		expr();
	}
}

void Parser::expr() {
	expratom();
	while( FIRST_binop(la.d_type) || la.d_type == Tok_Qmark || la.d_type == Tok_tick ) {
		if( FIRST_binop(la.d_type) ) {
			binop();
			expratom();
		} else if( la.d_type == Tok_Qmark ) {
			expect(Tok_Qmark, false, "expr");
			pattern();
		} else if( la.d_type == Tok_tick ) {
			expect(Tok_tick, false, "expr");
			exprCont();
		} else
			invalid("expr");
	}
}

void Parser::pattern() {
	patAtom();
	while( FIRST_patAtom(la.d_type) ) {
		patAtom();
	}
}

void Parser::patAtom() {
	if( FIRST_numlit(la.d_type) || la.d_type == Tok_Dot ) {
		if( FIRST_numlit(la.d_type) ) {
			numlit();
		} else if( la.d_type == Tok_Dot ) {
			expect(Tok_Dot, false, "patAtom");
		} else
			invalid("patAtom");
	}
	if( la.d_type == Tok_ident ) {
		expect(Tok_ident, false, "patAtom");
	} else if( la.d_type == Tok_string ) {
		expect(Tok_string, false, "patAtom");
	} else if( la.d_type == Tok_Lpar ) {
		expect(Tok_Lpar, false, "patAtom");
		patAlt();
		expect(Tok_Rpar, false, "patAtom");
	} else if( la.d_type == Tok_At ) {
		expect(Tok_At, false, "patAtom");
		expratom();
	} else
		invalid("patAtom");
}

void Parser::patAlt() {
	pattern();
	while( la.d_type == Tok_Comma ) {
		expect(Tok_Comma, false, "patAlt");
		pattern();
	}
}

void Parser::expratom() {
	if( FIRST_numlit(la.d_type) ) {
		numlit();
	} else if( la.d_type == Tok_string ) {
		expect(Tok_string, false, "expratom");
	} else if( la.d_type == Tok_ident ) {
		expect(Tok_ident, false, "expratom");
		if( la.d_type == Tok_Lpar ) {
			expect(Tok_Lpar, false, "expratom");
			exprlist();
			expect(Tok_Rpar, false, "expratom");
		}
	} else if( la.d_type == Tok_Hat ) {
		expect(Tok_Hat, false, "expratom");
		gvntail();
	} else if( FIRST_dollaritem(la.d_type) ) {
		dollaritem();
	} else if( la.d_type == Tok_Lpar ) {
		expect(Tok_Lpar, false, "expratom");
		expr();
		expect(Tok_Rpar, false, "expratom");
	} else if( FIRST_unaryop(la.d_type) ) {
		unaryop();
		expratom();
	} else if( la.d_type == Tok_At ) {
		expect(Tok_At, false, "expratom");
		expratom();
		if( ( peek(1).d_type == Tok_At && peek(2).d_type == Tok_Lpar )  ) {
			expect(Tok_At, false, "expratom");
			expect(Tok_Lpar, false, "expratom");
			exprlist();
			expect(Tok_Rpar, false, "expratom");
		}
	} else
		invalid("expratom");
}

void Parser::numlit() {
	if( la.d_type == Tok_integer ) {
		expect(Tok_integer, false, "numlit");
	} else if( la.d_type == Tok_real ) {
		expect(Tok_real, false, "numlit");
	} else
		invalid("numlit");
}

void Parser::gvntail() {
	if( la.d_type == Tok_ident ) {
		expect(Tok_ident, false, "gvntail");
		if( la.d_type == Tok_Lpar ) {
			expect(Tok_Lpar, false, "gvntail");
			exprlist();
			expect(Tok_Rpar, false, "gvntail");
		}
	} else if( la.d_type == Tok_Lpar ) {
		expect(Tok_Lpar, false, "gvntail");
		exprlist();
		expect(Tok_Rpar, false, "gvntail");
	} else if( la.d_type == Tok_At ) {
		expect(Tok_At, false, "gvntail");
		expratom();
		if( ( peek(1).d_type == Tok_At && peek(2).d_type == Tok_Lpar )  ) {
			expect(Tok_At, false, "gvntail");
			expect(Tok_Lpar, false, "gvntail");
			exprlist();
			expect(Tok_Rpar, false, "gvntail");
		}
	} else
		invalid("gvntail");
}

void Parser::dollaritem() {
	if( la.d_type == Tok_Dlr ) {
		expect(Tok_Dlr, false, "dollaritem");
		expect(Tok_ident, false, "dollaritem");
		if( la.d_type == Tok_Lpar ) {
			expect(Tok_Lpar, false, "dollaritem");
			funcargs();
			expect(Tok_Rpar, false, "dollaritem");
		}
	} else if( la.d_type == Tok_2Dlr ) {
		expect(Tok_2Dlr, false, "dollaritem");
		if( la.d_type == Tok_ident ) {
			expect(Tok_ident, false, "dollaritem");
		}
		if( ( peek(1).d_type == Tok_Hat && peek(2).d_type == Tok_ident )  ) {
			expect(Tok_Hat, false, "dollaritem");
			expect(Tok_ident, false, "dollaritem");
		}
		if( la.d_type == Tok_Lpar ) {
			expect(Tok_Lpar, false, "dollaritem");
			funcargs();
			expect(Tok_Rpar, false, "dollaritem");
		}
	} else
		invalid("dollaritem");
}

void Parser::funcargs() {
	if( FIRST_funcarg(la.d_type) ) {
		funcarg();
		while( la.d_type == Tok_Comma ) {
			expect(Tok_Comma, false, "funcargs");
			funcarg();
		}
	}
}

void Parser::funcarg() {
	expr();
	if( la.d_type == Tok_Hat ) {
		expect(Tok_Hat, false, "funcarg");
		routineref();
	}
	if( la.d_type == Tok_Colon ) {
		expect(Tok_Colon, false, "funcarg");
		expr();
	}
}

void Parser::unaryop() {
	if( la.d_type == Tok_Plus ) {
		expect(Tok_Plus, false, "unaryop");
	} else if( la.d_type == Tok_Minus ) {
		expect(Tok_Minus, false, "unaryop");
	} else if( la.d_type == Tok_tick ) {
		expect(Tok_tick, false, "unaryop");
	} else
		invalid("unaryop");
}

void Parser::binop() {
	if( la.d_type == Tok_Plus ) {
		expect(Tok_Plus, false, "binop");
	} else if( la.d_type == Tok_Minus ) {
		expect(Tok_Minus, false, "binop");
	} else if( la.d_type == Tok_Star ) {
		expect(Tok_Star, false, "binop");
	} else if( la.d_type == Tok_Slash ) {
		expect(Tok_Slash, false, "binop");
	} else if( la.d_type == Tok_bslash ) {
		expect(Tok_bslash, false, "binop");
	} else if( la.d_type == Tok_Hash ) {
		expect(Tok_Hash, false, "binop");
	} else if( la.d_type == Tok_5f ) {
		expect(Tok_5f, false, "binop");
	} else if( la.d_type == Tok_Amp ) {
		expect(Tok_Amp, false, "binop");
	} else if( la.d_type == Tok_Bang ) {
		expect(Tok_Bang, false, "binop");
	} else if( la.d_type == Tok_Lt ) {
		expect(Tok_Lt, false, "binop");
	} else if( la.d_type == Tok_Gt ) {
		expect(Tok_Gt, false, "binop");
	} else if( la.d_type == Tok_Eq ) {
		expect(Tok_Eq, false, "binop");
	} else if( la.d_type == Tok_Lbrack ) {
		expect(Tok_Lbrack, false, "binop");
	} else if( la.d_type == Tok_Rbrack ) {
		expect(Tok_Rbrack, false, "binop");
	} else
		invalid("binop");
}

void Parser::exprCont() {
	if( la.d_type == Tok_Qmark ) {
		expect(Tok_Qmark, false, "exprCont");
		pattern();
	} else if( la.d_type == Tok_Amp || la.d_type == Tok_Bang || la.d_type == Tok_Lt || la.d_type == Tok_Gt || la.d_type == Tok_Eq || la.d_type == Tok_Lbrack || la.d_type == Tok_Rbrack || la.d_type == Tok_Plus || la.d_type == Tok_Minus || la.d_type == Tok_Star || la.d_type == Tok_Slash || la.d_type == Tok_bslash || la.d_type == Tok_Hash || la.d_type == Tok_5f ) {
		if( la.d_type == Tok_Amp ) {
			expect(Tok_Amp, false, "exprCont");
		} else if( la.d_type == Tok_Bang ) {
			expect(Tok_Bang, false, "exprCont");
		} else if( la.d_type == Tok_Lt ) {
			expect(Tok_Lt, false, "exprCont");
		} else if( la.d_type == Tok_Gt ) {
			expect(Tok_Gt, false, "exprCont");
		} else if( la.d_type == Tok_Eq ) {
			expect(Tok_Eq, false, "exprCont");
		} else if( la.d_type == Tok_Lbrack ) {
			expect(Tok_Lbrack, false, "exprCont");
		} else if( la.d_type == Tok_Rbrack ) {
			expect(Tok_Rbrack, false, "exprCont");
		} else if( la.d_type == Tok_Plus ) {
			expect(Tok_Plus, false, "exprCont");
		} else if( la.d_type == Tok_Minus ) {
			expect(Tok_Minus, false, "exprCont");
		} else if( la.d_type == Tok_Star ) {
			expect(Tok_Star, false, "exprCont");
		} else if( la.d_type == Tok_Slash ) {
			expect(Tok_Slash, false, "exprCont");
		} else if( la.d_type == Tok_bslash ) {
			expect(Tok_bslash, false, "exprCont");
		} else if( la.d_type == Tok_Hash ) {
			expect(Tok_Hash, false, "exprCont");
		} else if( la.d_type == Tok_5f ) {
			expect(Tok_5f, false, "exprCont");
		} else
			invalid("exprCont");
		expratom();
	} else
		invalid("exprCont");
}

void Parser::glvn() {
	if( la.d_type == Tok_ident ) {
		expect(Tok_ident, false, "glvn");
		if( la.d_type == Tok_Lpar ) {
			expect(Tok_Lpar, false, "glvn");
			exprlist();
			expect(Tok_Rpar, false, "glvn");
		}
	} else if( la.d_type == Tok_Hat ) {
		expect(Tok_Hat, false, "glvn");
		gvntail();
	} else if( la.d_type == Tok_At ) {
		expect(Tok_At, false, "glvn");
		expratom();
		if( la.d_type == Tok_Lpar ) {
			expect(Tok_Lpar, false, "glvn");
			exprlist();
			expect(Tok_Rpar, false, "glvn");
		}
	} else
		invalid("glvn");
}

void Parser::lvar() {
	if( la.d_type == Tok_ident ) {
		expect(Tok_ident, false, "lvar");
		if( la.d_type == Tok_Lpar ) {
			expect(Tok_Lpar, false, "lvar");
			exprlist();
			expect(Tok_Rpar, false, "lvar");
		}
	} else if( la.d_type == Tok_At ) {
		expect(Tok_At, false, "lvar");
		expratom();
		if( la.d_type == Tok_Lpar ) {
			expect(Tok_Lpar, false, "lvar");
			exprlist();
			expect(Tok_Rpar, false, "lvar");
		}
	} else
		invalid("lvar");
}

