#ifndef __MPS_PARSER__
#define __MPS_PARSER__
// This file was automatically generated by EbnfStudio; don't modify it!

#include <Mumps/MpsToken.h>
#include <QList>

namespace Mps {

	class Scanner {
	public:
		virtual Token next() = 0;
		virtual Token peek(int offset) = 0;
	};

	class Parser {
	public:
		Parser(Scanner* s):scanner(s) {}
		void RunParser();
		struct Error {
		    QString msg;
		    int row, col;
		    QString path;
		    Error( const QString& m, int r, int c, const QString& p):msg(m),row(r),col(c),path(p){}
		};
		QList<Error> errors;
	protected:
		void Mumps76();
		void line();
		void label();
		void params();
		void command();
		void break_();
		void close_();
		void do_();
		void else_();
		void for_();
		void goto_();
		void halt_();
		void if_();
		void kill_();
		void lock_();
		void open_();
		void quit_();
		void read_();
		void set_();
		void use_();
		void useargs();
		void usearg();
		void view_();
		void write_();
		void xecute_();
		void new_();
		void job_();
		void zcmd_();
		void postcond();
		void doargs();
		void doarg();
		void gotoargs();
		void gotoarg();
		void forargs();
		void forarg();
		void killargs();
		void killarg();
		void lockargs();
		void lockarg();
		void nref();
		void openargs();
		void openarg();
		void openparams();
		void openparam();
		void readargs();
		void readarg();
		void readfmt();
		void readvar();
		void setargs();
		void setarg();
		void setdest();
		void writeargs();
		void writearg();
		void xecuteargs();
		void xecutearg();
		void newargs();
		void newarg();
		void jobargs();
		void viewargs();
		void viewgroup();
		void zargs();
		void entryref();
		void actuallist();
		void label_ref();
		void routineref();
		void exprlist();
		void expr();
		void pattern();
		void patAtom();
		void patAlt();
		void expratom();
		void numlit();
		void gvntail();
		void dollaritem();
		void funcargs();
		void funcarg();
		void unaryop();
		void binop();
		void exprCont();
		void glvn();
		void lvar();
	protected:
		Token cur;
		Token la;
		Scanner* scanner;
		void next();
		Token peek(int off);
		void invalid(const char* what);
		bool expect(int tt, bool pkw, const char* where);
	};
}
#endif // include
