#ifndef __MPS_TOKENTYPE__
#define __MPS_TOKENTYPE__
// This file was automatically generated by EbnfStudio; don't modify it!


#include <QByteArray>

namespace Mps {
	enum TokenType {
		Tok_Invalid = 0,

		TT_Literals,
		Tok_Bang,
		Tok_Hash,
		Tok_Dlr,
		Tok_2Dlr,
		Tok_Amp,
		Tok_Lpar,
		Tok_Rpar,
		Tok_Star,
		Tok_Plus,
		Tok_Comma,
		Tok_Minus,
		Tok_Dot,
		Tok_Slash,
		Tok_Colon,
		Tok_Lt,
		Tok_Eq,
		Tok_Gt,
		Tok_Qmark,
		Tok_At,
		Tok_Lbrack,
		Tok_Rbrack,
		Tok_Hat,
		Tok_5f,

		TT_Keywords,
		Tok_BREAK,
		Tok_CLOSE,
		Tok_DO,
		Tok_ELSE,
		Tok_FOR,
		Tok_GOTO,
		Tok_HALT,
		Tok_IF,
		Tok_JOB,
		Tok_KILL,
		Tok_LOCK,
		Tok_NEW,
		Tok_OPEN,
		Tok_QUIT,
		Tok_READ,
		Tok_SET,
		Tok_USE,
		Tok_VIEW,
		Tok_WRITE,
		Tok_XECUTE,
		Tok_ZCMD,

		TT_Specials,
		Tok_ident,
		Tok_integer,
		Tok_real,
		Tok_string,
		Tok_Newline,
		Tok_tick,
		Tok_bslash,
		Tok_CmdSep,
		Tok_Comment,
		Tok_Eof,

		TT_MaxToken,

		TT_Max
	};

	const char* tokenTypeString( int ); // Pretty with punctuation chars
	const char* tokenTypeName( int ); // Just the names without punctuation chars
	bool tokenTypeIsLiteral( int );
	bool tokenTypeIsKeyword( int );
	bool tokenTypeIsSpecial( int );
	TokenType tokenTypeFromString( const QByteArray& str, int* pos = 0 );
	TokenType tokenTypeFromString( const char* str, quint32 len, int* pos = 0 );
}
#endif // __MPS_TOKENTYPE__
