// This file was automatically generated by EbnfStudio; don't modify it!
#include "MpsTokenType.h"

namespace Mps {
	const char* tokenTypeString( int r ) {
		switch(r) {
			case Tok_Invalid: return "<invalid>";
			case Tok_Bang: return "!";
			case Tok_Hash: return "#";
			case Tok_Dlr: return "$";
			case Tok_2Dlr: return "$$";
			case Tok_Amp: return "&";
			case Tok_Lpar: return "(";
			case Tok_Rpar: return ")";
			case Tok_Star: return "*";
			case Tok_Plus: return "+";
			case Tok_Comma: return ",";
			case Tok_Minus: return "-";
			case Tok_Dot: return ".";
			case Tok_Slash: return "/";
			case Tok_Colon: return ":";
			case Tok_Lt: return "<";
			case Tok_Eq: return "=";
			case Tok_Gt: return ">";
			case Tok_Qmark: return "?";
			case Tok_At: return "@";
			case Tok_Lbrack: return "[";
			case Tok_Rbrack: return "]";
			case Tok_Hat: return "^";
			case Tok_5f: return "_";
			case Tok_BREAK: return "BREAK";
			case Tok_CLOSE: return "CLOSE";
			case Tok_DO: return "DO";
			case Tok_ELSE: return "ELSE";
			case Tok_FOR: return "FOR";
			case Tok_GOTO: return "GOTO";
			case Tok_HALT: return "HALT";
			case Tok_IF: return "IF";
			case Tok_JOB: return "JOB";
			case Tok_KILL: return "KILL";
			case Tok_LOCK: return "LOCK";
			case Tok_NEW: return "NEW";
			case Tok_OPEN: return "OPEN";
			case Tok_QUIT: return "QUIT";
			case Tok_READ: return "READ";
			case Tok_SET: return "SET";
			case Tok_USE: return "USE";
			case Tok_VIEW: return "VIEW";
			case Tok_WRITE: return "WRITE";
			case Tok_XECUTE: return "XECUTE";
			case Tok_ZCMD: return "ZCMD";
			case Tok_ident: return "ident";
			case Tok_integer: return "integer";
			case Tok_real: return "real";
			case Tok_string: return "string";
			case Tok_Newline: return "Newline";
			case Tok_tick: return "tick";
			case Tok_bslash: return "bslash";
			case Tok_CmdSep: return "CmdSep";
			case Tok_Comment: return "Comment";
			case Tok_Eof: return "<eof>";
			default: return "";
		}
	}
	const char* tokenTypeName( int r ) {
		switch(r) {
			case Tok_Invalid: return "Tok_Invalid";
			case Tok_Bang: return "Tok_Bang";
			case Tok_Hash: return "Tok_Hash";
			case Tok_Dlr: return "Tok_Dlr";
			case Tok_2Dlr: return "Tok_2Dlr";
			case Tok_Amp: return "Tok_Amp";
			case Tok_Lpar: return "Tok_Lpar";
			case Tok_Rpar: return "Tok_Rpar";
			case Tok_Star: return "Tok_Star";
			case Tok_Plus: return "Tok_Plus";
			case Tok_Comma: return "Tok_Comma";
			case Tok_Minus: return "Tok_Minus";
			case Tok_Dot: return "Tok_Dot";
			case Tok_Slash: return "Tok_Slash";
			case Tok_Colon: return "Tok_Colon";
			case Tok_Lt: return "Tok_Lt";
			case Tok_Eq: return "Tok_Eq";
			case Tok_Gt: return "Tok_Gt";
			case Tok_Qmark: return "Tok_Qmark";
			case Tok_At: return "Tok_At";
			case Tok_Lbrack: return "Tok_Lbrack";
			case Tok_Rbrack: return "Tok_Rbrack";
			case Tok_Hat: return "Tok_Hat";
			case Tok_5f: return "Tok_5f";
			case Tok_BREAK: return "Tok_BREAK";
			case Tok_CLOSE: return "Tok_CLOSE";
			case Tok_DO: return "Tok_DO";
			case Tok_ELSE: return "Tok_ELSE";
			case Tok_FOR: return "Tok_FOR";
			case Tok_GOTO: return "Tok_GOTO";
			case Tok_HALT: return "Tok_HALT";
			case Tok_IF: return "Tok_IF";
			case Tok_JOB: return "Tok_JOB";
			case Tok_KILL: return "Tok_KILL";
			case Tok_LOCK: return "Tok_LOCK";
			case Tok_NEW: return "Tok_NEW";
			case Tok_OPEN: return "Tok_OPEN";
			case Tok_QUIT: return "Tok_QUIT";
			case Tok_READ: return "Tok_READ";
			case Tok_SET: return "Tok_SET";
			case Tok_USE: return "Tok_USE";
			case Tok_VIEW: return "Tok_VIEW";
			case Tok_WRITE: return "Tok_WRITE";
			case Tok_XECUTE: return "Tok_XECUTE";
			case Tok_ZCMD: return "Tok_ZCMD";
			case Tok_ident: return "Tok_ident";
			case Tok_integer: return "Tok_integer";
			case Tok_real: return "Tok_real";
			case Tok_string: return "Tok_string";
			case Tok_Newline: return "Tok_Newline";
			case Tok_tick: return "Tok_tick";
			case Tok_bslash: return "Tok_bslash";
			case Tok_CmdSep: return "Tok_CmdSep";
			case Tok_Comment: return "Tok_Comment";
			case Tok_Eof: return "Tok_Eof";
			default: return "";
		}
	}
	bool tokenTypeIsLiteral( int r ) {
		return r > TT_Literals && r < TT_Keywords;
	}
	bool tokenTypeIsKeyword( int r ) {
		return r > TT_Keywords && r < TT_Specials;
	}
	bool tokenTypeIsSpecial( int r ) {
		return r > TT_Specials && r < TT_Max;
	}
	static inline char at( const char* str, quint32 len, int i ){
		return ( i < len ? str[i] : 0 );
	}
	TokenType tokenTypeFromString( const QByteArray& str, int* pos ) {
		return tokenTypeFromString(str.constData(),str.size(),pos);
	}
	TokenType tokenTypeFromString( const char* str, quint32 len, int* pos ) {
		int i = ( pos != 0 ? *pos: 0 );
		TokenType res = Tok_Invalid;
		switch( at(str,len,i) ){
		case '!':
			res = Tok_Bang; i += 1;
			break;
		case '#':
			res = Tok_Hash; i += 1;
			break;
		case '$':
			if( at(str,len,i+1) == '$' ){
				res = Tok_2Dlr; i += 2;
			} else {
				res = Tok_Dlr; i += 1;
			}
			break;
		case '&':
			res = Tok_Amp; i += 1;
			break;
		case '(':
			res = Tok_Lpar; i += 1;
			break;
		case ')':
			res = Tok_Rpar; i += 1;
			break;
		case '*':
			res = Tok_Star; i += 1;
			break;
		case '+':
			res = Tok_Plus; i += 1;
			break;
		case ',':
			res = Tok_Comma; i += 1;
			break;
		case '-':
			res = Tok_Minus; i += 1;
			break;
		case '.':
			res = Tok_Dot; i += 1;
			break;
		case '/':
			res = Tok_Slash; i += 1;
			break;
		case ':':
			res = Tok_Colon; i += 1;
			break;
		case '<':
			res = Tok_Lt; i += 1;
			break;
		case '=':
			res = Tok_Eq; i += 1;
			break;
		case '>':
			res = Tok_Gt; i += 1;
			break;
		case '?':
			res = Tok_Qmark; i += 1;
			break;
		case '@':
			res = Tok_At; i += 1;
			break;
		case 'B':
			if( at(str,len,i+1) == 'R' ){
				if( at(str,len,i+2) == 'E' ){
					if( at(str,len,i+3) == 'A' ){
						if( at(str,len,i+4) == 'K' ){
							res = Tok_BREAK; i += 5;
						}
					}
				}
			}
			break;
		case 'C':
			if( at(str,len,i+1) == 'L' ){
				if( at(str,len,i+2) == 'O' ){
					if( at(str,len,i+3) == 'S' ){
						if( at(str,len,i+4) == 'E' ){
							res = Tok_CLOSE; i += 5;
						}
					}
				}
			}
			break;
		case 'D':
			if( at(str,len,i+1) == 'O' ){
				res = Tok_DO; i += 2;
			}
			break;
		case 'E':
			if( at(str,len,i+1) == 'L' ){
				if( at(str,len,i+2) == 'S' ){
					if( at(str,len,i+3) == 'E' ){
						res = Tok_ELSE; i += 4;
					}
				}
			}
			break;
		case 'F':
			if( at(str,len,i+1) == 'O' ){
				if( at(str,len,i+2) == 'R' ){
					res = Tok_FOR; i += 3;
				}
			}
			break;
		case 'G':
			if( at(str,len,i+1) == 'O' ){
				if( at(str,len,i+2) == 'T' ){
					if( at(str,len,i+3) == 'O' ){
						res = Tok_GOTO; i += 4;
					}
				}
			}
			break;
		case 'H':
			if( at(str,len,i+1) == 'A' ){
				if( at(str,len,i+2) == 'L' ){
					if( at(str,len,i+3) == 'T' ){
						res = Tok_HALT; i += 4;
					}
				}
			}
			break;
		case 'I':
			if( at(str,len,i+1) == 'F' ){
				res = Tok_IF; i += 2;
			}
			break;
		case 'J':
			if( at(str,len,i+1) == 'O' ){
				if( at(str,len,i+2) == 'B' ){
					res = Tok_JOB; i += 3;
				}
			}
			break;
		case 'K':
			if( at(str,len,i+1) == 'I' ){
				if( at(str,len,i+2) == 'L' ){
					if( at(str,len,i+3) == 'L' ){
						res = Tok_KILL; i += 4;
					}
				}
			}
			break;
		case 'L':
			if( at(str,len,i+1) == 'O' ){
				if( at(str,len,i+2) == 'C' ){
					if( at(str,len,i+3) == 'K' ){
						res = Tok_LOCK; i += 4;
					}
				}
			}
			break;
		case 'N':
			if( at(str,len,i+1) == 'E' ){
				if( at(str,len,i+2) == 'W' ){
					res = Tok_NEW; i += 3;
				}
			}
			break;
		case 'O':
			if( at(str,len,i+1) == 'P' ){
				if( at(str,len,i+2) == 'E' ){
					if( at(str,len,i+3) == 'N' ){
						res = Tok_OPEN; i += 4;
					}
				}
			}
			break;
		case 'Q':
			if( at(str,len,i+1) == 'U' ){
				if( at(str,len,i+2) == 'I' ){
					if( at(str,len,i+3) == 'T' ){
						res = Tok_QUIT; i += 4;
					}
				}
			}
			break;
		case 'R':
			if( at(str,len,i+1) == 'E' ){
				if( at(str,len,i+2) == 'A' ){
					if( at(str,len,i+3) == 'D' ){
						res = Tok_READ; i += 4;
					}
				}
			}
			break;
		case 'S':
			if( at(str,len,i+1) == 'E' ){
				if( at(str,len,i+2) == 'T' ){
					res = Tok_SET; i += 3;
				}
			}
			break;
		case 'U':
			if( at(str,len,i+1) == 'S' ){
				if( at(str,len,i+2) == 'E' ){
					res = Tok_USE; i += 3;
				}
			}
			break;
		case 'V':
			if( at(str,len,i+1) == 'I' ){
				if( at(str,len,i+2) == 'E' ){
					if( at(str,len,i+3) == 'W' ){
						res = Tok_VIEW; i += 4;
					}
				}
			}
			break;
		case 'W':
			if( at(str,len,i+1) == 'R' ){
				if( at(str,len,i+2) == 'I' ){
					if( at(str,len,i+3) == 'T' ){
						if( at(str,len,i+4) == 'E' ){
							res = Tok_WRITE; i += 5;
						}
					}
				}
			}
			break;
		case 'X':
			if( at(str,len,i+1) == 'E' ){
				if( at(str,len,i+2) == 'C' ){
					if( at(str,len,i+3) == 'U' ){
						if( at(str,len,i+4) == 'T' ){
							if( at(str,len,i+5) == 'E' ){
								res = Tok_XECUTE; i += 6;
							}
						}
					}
				}
			}
			break;
		case 'Z':
			if( at(str,len,i+1) == 'C' ){
				if( at(str,len,i+2) == 'M' ){
					if( at(str,len,i+3) == 'D' ){
						res = Tok_ZCMD; i += 4;
					}
				}
			}
			break;
		case '[':
			res = Tok_Lbrack; i += 1;
			break;
		case ']':
			res = Tok_Rbrack; i += 1;
			break;
		case '^':
			res = Tok_Hat; i += 1;
			break;
		case '_':
			res = Tok_5f; i += 1;
			break;
		}
		if(pos) *pos = i;
		return res;
	}
}
