BACKCRG ;DSM11 UTILITIES; COPYRIGHT 1980 DEC
        Q
DKASKT  S SUB="0,BACKUP,'NM,'DKK,TO,UNIT" D DEF^SYSROU
DKAT2   S:$D(@SYV) DEF=@SYV S QUES="TOQ" X ^%Q("ASK") S:ANS="" %A=1 Q:%A
        I ANS=FRM W !,"  THE ""TO"" DISK CANNOT BE IN THE SAME DRIVE AS THE "
        I  W """FROM"" DISK!",! S %A=1 Q
        S DTN2=$F(TYPES,$E(ANS,1,2))\3-1,DU2=$E(ANS,3)
        I ANS'?2A1N!(DTN2<0)!(DU2>7)!(DTN2=4&(DU2>3)) D TOQH G DKAT2
        S @SYV=ANS
VER     S SUB="0,BACKUP,'NM,'DKK,VERIFY" D DEF^SYSROU
        I DEF="" S DEF="N" S:$V($V(44)+71) DEF="Y"
        S QUES="VEQ" X ^%Q("ASKYN") G:%A DKASKT S @SYV=ANS
        W ! Q
TOQ     W !,"WHICH DRIVE WILL HOLD THE BACKUP DISK" Q
TOQH    W !,"ENTER THE 3-CHARACTER DESIGNATION (FOR EXAMPLE: DM2) OF "
        W "THE DRIVE/UNIT",!
        W !,"THAT WILL HOLD THE DISK ON WHICH THE INFORMATION BEING BACKED "
        W "UP WILL BE",!,"WRITTEN.",! Q
VEQ     W !,"DO YOU WISH TO VERIFY" Q
VEQH    W !,"IF YOU ANSWER 'Y' TO THIS QUESTION, THE DISK HARDWARE ""WRITE-"
        W "CHECK-AFTER-",!
        W "WRITE"" FEATURE WILL BE ENABLED FOR THIS BACKUP, CAUSING ALL DISK "
        W "BLOCKS",!
        W "WRITTEN TO BE RE-READ AND CHECKED TO SEE THAT THE DATA WAS WRITTEN "
        W "CORRECTLY.",!
        W "IF YOU ANSWER 'N', THE ""WRITE-CHECK-AFTER-WRITE"" FEATURE WILL BE "
        W "DISABLED FOR",!
        W "THIS BACKUP.  (IN EITHER CASE, THE ORIGINAL SETTING WILL BE "
        W "RESTORED AFTER",!
        W "ALL BACKUPS ARE COMPLETE.)",!!
        W "IF YOU ANSWER 'Y', IT WILL ADD ABOUT 40 PERCENT TO THE TIME REQUIRED "
        W "FOR",!,"THIS BACKUP.",!! Q
SYBAS   W !,"YOU MAY NOT BACK UP DISK ",D,", LABEL= "
        W ^SYS(0,"BACKUP",NM,"DISK "_DK,"FROM","MASTER LABEL"),!
        W "WHILE RUNNING THE BASELINE SYSTEM.  THE ONLY DISK YOU MAY BACK "
        W "UP WHILE",!
        W "RUNNING THE BASELINE SYSTEM IS YOUR SYSTEM DISK ITSELF.",!
        W "YOUR PRESENT SYSTEM DISK IS:  ",SYU,", LABEL= ",M,!!
        W "TO BACK UP ANY DISK OTHER THAN THE SYSTEM DISK, YOU MUST BE "
        W "RUNNING SOME",!
        W "CONFIGURATION OTHER THAN THE BASELINE SYSTEM.",!
        S %FAIL=4 Q
