BACKCRE ;DSM11 UTILITIES; COPYRIGHT 1980 DEC
        Q
START   S DEF="",QUES="NMQ" W ! X ^%Q("ASK") Q:ANS=""!%A
        S NM=ANS I $L(NM)>12!'$L(NM) D NMQH G START
        I NM="*" D NAMHLP^BACKUP G START
        I '$D(^SYS(0,"BACKUP",NM)) W !,"CREATE" G EDCR
EXIST   S QUES="EX" X ^%Q("ASKN") G START:%A
        I ANS="N" W !,"EDIT" G EDCR
        S QUES="SURQ" X ^%Q("ASKN") G START:%A
        I ANS="Y" K ^SYS(0,"BACKUP",NM)
        Q
EDCR    W " COMMAND FILE """,NM,"""",!
        S SU="0,BACKUP,'NM"
NUM     S SUB=SU_",DISKS/1",QUES="HMNY" D DEF^SYSROU X ^%Q("ASK")
        G START:%A I ANS'?1N!(ANS<1) D HMNYH G NUM
        S NUM=ANS
DISKS   D TYPES^SYSROU
        F DK=1:1:NUM W !! D DKASK^BACKCRF G START:ANS=""!%A
        S ^SYS(0,"BACKUP",NM,"DISKS")=NUM F DK=NUM+1:1:9 K ^SYS(0,"BACKUP",NM,"DISK "_DK)
        D ASKJRN^BACKJRN G NUM:%A
        W !!,"** BACKUP-COMMAND-FILE """,NM,""" IS NOW COMPLETE"
        W !!,"  WHEN YOU WISH TO ACTUALLY PERFORM THIS BACKUP, SELECT OPTION "
        W "NUMBER",!
        W "  2 OR 3 (PERFORM BACKUP), AND ENTER NAME """,NM,""" **",!!!
        K  Q
NMQ     W "ENTER THE NAME OF THE BACKUP-COMMAND-FILE YOU WISH TO EDIT,"
        W !,"CREATE, OR DELETE" Q
NMQH    W "THE NAME MUST CONSIST OF UP TO 12 CHARACTERS.  THIS IS THE NAME "
        W "YOU WILL",!
        W "REFER TO THIS BACKUP COMMAND FILE BY WHEN YOU WISH TO ACTUALLY "
        W "PERFORM",!,"THE BACKUP.",!
        W "(IF YOU WOULD LIKE A LIST OF THE NAMES OF ALL EXISTING "
        W "BACKUP-COMMAND-",!
        W "FILES, ENTER  '*' )",! Q
EX      W !,"FILE """,NM,""" ALREADY EXISTS."
        W !,"DO YOU WISH TO DELETE THIS FILE" Q
EXH     W !,"ENTER ""Y"" ONLY IF YOU NO LONGER NEED BACKUP-COMMAND-FILE """
        W NM,""" AND YOU NOW",!,"WISH TO DELETE IT.",! Q
SURQ    W "  ARE YOU SURE" Q
HMNY    W !,"HOW MANY DISKS WILL YOU BE BACKING UP" Q
HMNYH   W !,"ENTER A NUMBER FROM 1 TO 9, OR ENTER  <CR>  IF YOU HAVE "
        W "CHANGED YOUR MIND",! Q
