BACKMGA ;DSM11 UTILITIES; COPYRITHT 1980 DEC
        Q
MTASKN  S SUB="0,BACKUP,'NM,'DKK,TO,MAGTAPE UNIT/0" D DEF^SYSROU
MTASK2  S QUES="MDRQ",DEF=1 S:$D(@SYV) DEF=$L(@SYV,";") X ^%Q("ASK") Q:%A
        I ANS'?1N!(ANS<1)!(ANS>4) D MDRQH G MTASK2
        S DRVNR=ANS F I=1:1:DRVNR D MAGASK G:%A MTASK2
        S @SYV=$P(@SYV,";",1,I) G MT2
MAGASK  ;
UT2     S DEF="" S:$D(@SYV) DEF=$P(@SYV,";",I) S QUES="MTQ" X ^%Q("ASK") S:ANS="" %A=1 Q:%A  I ANS'?1N!(ANS>3) D MTQH G UT2
        I $D(@SYV) S @SYV=$P(@SYV,";",1,I-1)_$S(I-1:";",1:"")_ANS_";"_$P(@SYV,";",I+1,999)
        E  S @SYV=ANS
        Q
MT2     S SUB="0,BACKUP,'NM,'DKK,TO,MAGTAPE DENSITY/800" D DEF^SYSROU
DN2     S QUES="DENQ" X ^%Q("ASK") Q:%A  I ANS'=800,ANS'=1600,ANS'=6250 D DENQH G DN2
        S @SYV=ANS
        S SUB="0,BACKUP,'NM,'DKK,TO,MAGTAPE BLOCK FACTOR/31" D DEF^SYSROU
BL2     S QUES="BLFQ" X ^%Q("ASK") Q:%A
        I ANS'?1N.N!(ANS>31) D BLFQH G BL2
        S @SYV=ANS
        Q
MDRQ    W !,"HOW MANY TAPE DRIVES WILL BE USED FOR BACKUP" Q
MDRQH   W !,"ENTER A NUMBER FROM 1 TO 4",! Q
MTQ     I DRVNR=1 W !,"WHICH MAGTAPE UNIT DO YOU WISH TO USE (0, 1, 2, OR 3)" Q
        W !,"ENTER ",$P("1st,2nd,3rd,4th",",",I)," MAGTAPE UNIT YOU WISH TO USE" Q
MTQH    W !,"BACKUP COMMAND FILE """,NM,""" SPECIFIES THAT ONE OR MORE "
        W "BACKUPS ARE",!
        W "TO BE DONE TO MAGTAPE.",! Q
DENQ    W !,"DENSITY - 800, 1600, OR 6250 BPI  " Q
DENQH   W !,"IF TAPE DRIVE IS TU80/TS11/TS05, YOU WILL GET 1600 BPI NO MATTER WHAT "
        W "YOU ANSWER.",!
        W "IF TAPE DRIVE IS TS03, YOU WILL GET 800 BPI NO MATTER WHAT YOU "
        W "ANSWER.",!
        W "IF TAPE DRIVE IS TE16/TU77, YOU MAY SELECT EITHER 800 OR 1600.",!
        W "IF TAPE DRIVE IS TU81, YOU MAY SELECT EITHER 1600 OR 6250.",!
        W "HIGHER DENSITY USES PROPORTIONATELY LESS TAPE, BUT "
        W "THE TAPE MAY",!
        W "NOT HOLD THE INFORMATION QUITE AS RELIABLY IF THE TAPE IS "
        W "OF LOW QUALITY.",! Q
BLFQ    W !,"BLOCKING FACTOR DESIRED" Q
BLFQH   W !,"A BLOCKING FACTOR OF ""N"" MEANS ""N"" DSM DISK BLOCKS "
        W "WILL BE WRITTEN IN",!
        W "EACH PHYSICAL MAGTAPE BLOCK.  A HIGHER BLOCKING FACTOR IS MORE "
        W "EFFICIENT,",!,"BUT MAY CAUSE MORE TAPE ERRORS.",!
        W "THE ALLOWABLE RANGE OF NUMBERS IS 1-31.",!!
        W "IF YOU ARE NOT SURE WHAT TO ANSWER, SIMPLY TYPE  <CR>  TO "
        W "ACCEPT THE",!
        W "DEFAULT VALUE.",!! Q
