BACKMM  Q  ;DSM11 Utilities; Copyright 1980 DEC
MAGSET  ;
MAGQ    G:$D(UNATTN) CHK S QUES="MOU",DEF="" X ^%Q("EN") I %A S E=1 Q
        I ANS'="" D MOUH G MAGQ
CHK     S ZT=$ZT,$ZT="" U UU W *5,*10 S ZA=$ZA U 0 S $ZT=ZT
        I ZA\64#2=0 G:$D(UNATTN) MAGER1 W !,"** TAPE NOT READY! **",! G MAGQ
        I ZA\4#2 G:$D(UNATTN) MAGER2 W !,"** TAPE IS WRITE-PROTECTED! **",! G MAGQ
        Q
MOU     W !,"Please mount the tape that will hold the backed up infomation,"
        W !,"  on Magtape Unit #",UU-47,"   * WRITE-ENABLED *  (Ring In)"
        W !,"  then type  <CR>" Q
MOUH    W !,"Type  ""^""  if you have changed your mind and do not wish to "
        W "proceed with",!,"the Backup.",! Q
WRT     D HD^BACKUP S $ZT="RET",= Q
MAGER1  S MSG="TAPE NOT READY.  UNATTENDED BACKUP ABORTED" G WRT
MAGER2  S MSG="TAPE IS WRITE-PROTECTED.  UNATTENDED BACKUP ABORTED" G WRT
MAGER3  S MSG="TAPE UNIT "_(UU-47)_" IS UNAVAILABLE.  UNATTENDED BACKUP ABORTED" G WRT
ERROR1  S MSG="INCORRECT DISK MOUNTED.  UNATTENDED BACKUP ABORTED" G WRT
ERROR2  S MSG="NOT A DSM11 V3 DISK.  UNATTENDED BACKUP ABORTED" G WRT
ERROR3  S MSG="NOT A MASTER DISK! - HAS BACKUP" G S2
S1      S MSG=MSG_" DISK! - HAS MASTER"
S2      S MSG=MSG_" LABEL: "_M G WRT
ERROR4  S MSG="WRONG" G S1
ERROR5  S MSG=$E($ZE,1,7)_"  WHILE TRYING TO READ DISK LABEL" G WRT
ERROR6  S MSG="! ERROR: "_$ZE_". READING NEAR BLK # "_F_":"_FD_FU G WRT
ERROR7  S MSG="ERROR: "_$ZE G WRT
ERROR8  S MSG="OUT OF SPACE ON TAPE.  UNATTENDED BACKUP ABORTED" G WRT
ERROR9  S MSG="! TAPE ERROR !  $ZA= "_ZA_" (DECIMAL). APPX. "_(F-FB)_" BLKS PROCESSED." G WRT
ERROR10 S MSG=$E($ZE,1,7)_"  WHILE TRYING TO "_A_" LABEL" G WRT
ERROR11 S MSG="! ERROR: "_$ZE_",  "_A_"ING NEAR BLK # "_B G WRT
ERROR12 S MSG="OUT OF SPACE ON BACKUP DISK.  UNATTENDED BACKUP ABORTED" G WRT
RET     G BACFAIL^BACKUPDO
