BACKUPPR        ;DSM11 UTILITIES; COPYRIGHT 1980 DEC
        Q
PREPARE ;
        C 63 O 63::3 G NBUSY:$T
        I $D(UNATTN) D MESSG1,HD^BACKUP,SETG
        E  W !,"VIEW BUFFER IS BUSY - CANNOT PROCEED.",!
        C 63 K  Q
NBUSY   S ST=$V(44),H=256
        S BF=$V(ST+32)-5 S:BF<3 BF=3 S:BF>127 BF=127 S:BF>63&(UU'<47) BF=63 C 63 O 63:BF:1 G GOTB:$T
        F BF=BF-1:-1:2 C 63 O 63:BF:0 G GOTB:$T
        I $D(UNATTN) D MESSG2,HD^BACKUP,SETG C 63 K  Q
        W !,"! ONLY ONE BUFFER IS AVAILABLE.  NEED AT LEAST TWO BUFFERS TO "
        W "PROCEED.",!,"  -- PLEASE TRY AGAIN LATER.",!! C 63 K  Q
GOTB    ;
        D QUIET^SYSWAIT G ACTIV:%FAIL V ST::$V(ST)+8192 D RELSYS^SYSWAIT
        B 2 S $ZT="QERR^BACKUPPR"
SHOW    D LOG^BACKLOGO G STOP:ANS'="Y"!%A
        D JTEST^BACKUNJR G STOP:JSW=-10
        I UU'<47 C UU O UU:"B"
BAK     B 0
        V:'QU ST::%STSAV
        S %NP=1 D ^%D S DA=$J(%DAT,9)
        W:'$D(UNATTN) !,"(PROCEEDING WITH ",BF," BUFFERS)",!
        K (NUM,TYPES,ID,SYU,NM,%STSAV,BF,ST,FM,UU,QU,JIX,JSW,E,DA,H,UNATTN,DSKNO,DKCNT,MTCNT)
        S WT=$V(ST+71)
        S V=ST+310,W0=$V(V)\4*4+($V(V)#2)
        S Q=""""
        G DOBACKS^BACKUPDO
ACTIV   W:'$D(UNATTN) !! G ABO:%FAIL<0
        I $D(UNATTN) D MESSG3,HD^BACKUP G ABO
        W "IMPORTANT SYSTEM PROCESSES ARE STILL ACTIVE.  PLEASE TRY AGAIN IN "
        W "ABOUT ",!
        W "20-30 SECONDS.",! G ABO
QERR    U 0 I $D(UNATTN) D MESSG4,HD^BACKUP G ABO
        W ! I $ZE'?1"<INRPT".E W "! UNEXPECTED ERROR:",!
        W $ZE,! S E=6 G ABO
STOP    U 0 W:'$D(UNATTN) !,"STOPPING.",! G ABO
MESSG1  S MSG="VIEW BUFFER IS BUSY - CANNOT PROCEED." Q
MESSG2  S MSG="! ONLY ONE BUFFER IS AVAILABLE.  NEED AT LEAST TWO BUFFERS TO PROCEED." Q
MESSG3  S MSG="! IMPORTANT SYSTEM PROCESSES STILL ACTIVE.  UNATTENDED BACKUP ABORTED" Q
MESSG4  S MSG="! UNEXPECTED ERROR: "_$ZE Q
SETG    S ^SYS(0,"UNATTENDED BACKUP",NM,+$H,$P($H,",",2))=MSG Q
ABO     ;
ACDON   C:UU'<47 UU
        I $D(JSW) I JSW=-1!(JSW=-2) D RESTART^BACKUNJR
        C 63 I $D(%STSAV) V $V(44)::%STSAV
        G:'$D(UNATTN) EX I $D(MSG) D SETG
        E  S ^SYS(0,"UNATTENDED BACKUP",NM,+$H,$P($H,",",2))="FINISHED"
EX      B 1 B -2 Q
