BACKCRF ;DSM11 UTILITIES; COPYRIGHT 1980 DEC
        Q
AGAIN   W !,"***",!
DKASK   S DKK="DISK "_DK,SUB="0,BACKUP,'NM,'DKK,FROM,UNIT" D DEF^SYSROU
DKA2    S QUES="BKQ" X ^%Q("ASK") Q:ANS=""!%A
        S DTY=$E(ANS,1,2),DU=$E(ANS,3),DTN=$F(TYPES,DTY)\3-1
        I ANS'?2A1N!(DTN<0)!(DU>7)!(DU>3&(DTN=4)) D BKQH G DKA2
        S FRM=ANS,@SYV=FRM
LA2     S SUB="0,BACKUP,'NM,'DKK,FROM,MASTER LABEL" D DEF^SYSROU
        S QUES="LAQ" X ^%Q("ASK") Q:ANS=""!%A
        I $L(ANS)<3!($L(ANS)>24)!(ANS'?1"""".E1"""") D LAQH G LA2
        S @SYV=ANS
IU2     S SUB="0,BACKUP,'NM,'DKK,MODE/ALL" D DEF^SYSROU
        S QUES="ALIU" X ^%Q("ASK") Q:%A  S:ANS="AL" ANS="ALL"
        I ANS'="ALL",ANS'="IU" W "  TYPE '?' FOR HELP",! G IU2
        S @SYV=ANS
DT2     S SUB="0,BACKUP,'NM,'DKK,TO/D" D DEF^SYSROU
        S QUES="DTQ" X ^%Q("ASK") Q:ANS=""!%A
        I $E(ANS,1)="D","DISK"[ANS S ANS="D"
        I $E(ANS,1)="M","MAGTAPE"[ANS S @SYV="M" D MTASKN^BACKMGA G DT2:%A Q
        I ANS'="D" D DTQH G DT2
        S @SYV="D" D DKASKT^BACKCRG G AGAIN:%A
        Q
BKQ     W "WHICH DRIVE WILL CONTAIN THE "
        W:NUM>1 $P("1st,2nd,3rd,4th,5th,6th,7th,8th,9th",",",DK)," "
        W "DISK TO BE BACKED UP" Q
BKQH    W !,"ENTER THE THREE-CHARACTER DESIGNATION (FOR EXAMPLE: DM1) OF "
        W "THE DRIVE/UNIT",!
        W "THAT WILL HOLD THIS DISK WHEN IT IS TIME TO BACK IT UP.",!
        Q:DK=1
        W "(NOTE: THIS MAY BE THE SAME AS A DRIVE/UNIT USED FOR A PREVIOUS DISK"
        W " IN THIS",!,"COMMAND FILE.)",! Q
LAQ     W "WHAT WILL THIS DISK'S MASTER LABEL BE" Q
LAQH    W !,"ENTER THE STRING OF UP TO 22 CHARACTERS, ENCLOSED IN QUOTES.",!
        W "(WHEN THIS COMMAND FILE IS EXECUTED, THIS LABEL WILL BE VERIFIED, "
        W "AND",!
        W "THE BACKUP OPERATION WILL NOT BE ALLOWED TO PROCEED IF THE WRONG "
        W "DISK",!,"IS MOUNTED.)",! Q
DTQ     W !,"WILL YOU BE BACKING THIS DISK UP TO ANOTHER DISK,"
        W !,"OR TO MAGTAPE [ D OR M ]" Q
DTQH    W !,"ENTER 'D' IF THE DEVICE YOU WILL BE BACKING THIS DISK UP TO "
        W "WILL BE A DISK.",!
        W "ENTER 'M' IF IT WILL BE A MAGTAPE.",! Q
ALIU    W !,"BACKUP ""IN-USE"" OR ""ALL"" DSM DISK BLOCKS [ALL or IU]" Q
ALIUH   W !,"THE ""ALL"" BACKUP OPTION DOES A COMPLETE PHYSICAL BACKUP"
        W !,"OF A DISK VOLUME REGARDLESS OF WHETHER THE VOLUME IS COMPLETELY"
        W !,"FILLED WITH DATA OR NOT.  IF THE SIZE OF THE MASTER DISK"
        W !,"VOLUME DOES NOT EXCEED THE CAPACITY OF THE BACKUP DISK VOLUME,"
        W !,"AND THE MASTER DISK CONTAINS A BOOTABLE SYSTEM, THE RESULTING"
        W !,"BACKUP VOLUME WILL ALSO BE BOOTABLE.",!
        W !,"IN-USE BLOCKS INCLUDE ALL JOURNAL, SPOOL, AND SDP BLOCKS, AS WELL AS"
        W !,"ALL BLOCKS CURRENTLY IN USE FOR THE STORAGE OF GLOBALS AND "
        W "ROUTINES, AND",!
        W "ALSO ANY BLOCKS (SUCH AS THE MAP BLOCKS THEMSELVES) THAT ARE "
        W "OWNED BY THE",!
        W "SYSTEM.",!
        W !,"IN-USE BACKUP MAY TAKE LONGER THAN ""ALL"" BACKUP PROCEDURES WHEN"
        W !,"BACKING UP A MASTER VOLUME WHICH IS ESSENTIALLY FULL.",!
        Q
