BACKPRT ;YZH;1-OCT-83;SCHEDULED BACKUP ERROR REPORTER
START   I '$D(^SYS(0,"UNATTENDED BACKUP")) W !!?5,"SCHEDULED BACKUP HAS NEVER BEEN RUN.",! Q
        S %QTY=2,%DEF=0 D ^%IOS G:'$D(%IOD) EXIT
        I "^SC^LP^TRM"'[%DTY!(%DTY="") W !?5,"IMPROPER DEVICE SELECTION" U 0 C:%IOD'=$I %IOD G START
STDAT   R !,"STARTING DATE (DD-MMM-YY) <FIRST ENTRY> ",%DT G:%DT="^" START
        I %DT="" S %DAT=-1 G STTIM
        D %CDN^%H I '$D(%DAT) W !?5,"ENTER DATE IN REQUESTED FORMAT." G STDAT
STTIM   R !,"STARTING TIME (HH:MM) <FIRST ENTRY> ",%TM G:%TM="^" STDAT
        I %TM="" S %TIM=-1 G PRINT
        D %CTN^%H I '$D(%TIM) W !?5,"ENTER TIME IN REQUESTED FORMAT." G STTIM
PRINT   S SDAT=%DAT,STIM=%TIM U %IOD
        S REPORT="^SYS(0,""UNATTENDED BACKUP"",-1)" F I=0:0 S REPORT=$ZN(@REPORT) Q:$P(REPORT,",",2)'="""UNATTENDED BACKUP"""  D LIST
        W # U 0 Q
LIST    S %DT=$P(REPORT,",",4),%TM=+$P(REPORT,",",5) Q:%DT'?1N.N!(%TM'?1N.N)
        Q:%DT<SDAT  I %DT=SDAT Q:%TM<STIM
        S FILNM=$P(REPORT,"""",4) D %CTS^%H,%CDS^%H
        I @REPORT="STARTED" W !!,%DAT,"  ",%TIM,?25,"BACKUP-COMMAND-FILE '",FILNM,"' STARTED" Q
        I @REPORT="FINISHED" W !!,%DAT,"  ",%TIM,?25,"BACKUP-COMMAND-FILE '",FILNM,"' FINISHED" Q
        W !!,%DAT,"  ",%TIM,?25,"BACKUP-COMMAND-FILE '",FILNM,"' ERROR: ",!?25,@REPORT Q
EXIT    U 0 I $D(%IOD) C:%IOD'=$I %IOD
        K %IOD,%QTY,%DTY Q
