BACKLOGO        Q  ;DSM11 UTILITIES; COPYRIGHT 1980 DEC
LOG     I %JO=""!$D(UNATTN) S ANS="Y",%A=0 G RET
        S %SSD=0 G L1
%SSD    ;
        S %SSD=1
L1      W !!,"THE FOLLOWING JOBS ARE STILL LOGGED IN:",!!
        W "  JOB #     PRINCIPAL DEVICE     ROUTINE",!!
L2      S %J=$P(%JO,",",1),%JO=$P(%JO,",",2,128) I %J'="" D LISTJ G L2
        W ! G RET:%SSD
        S QUES="PROQ" X ^%Q("ASKY")
RET     K %I,%J,%RNAM,%JO,%SSD Q
LISTJ   S %RNAM=""
        F %I=126:1:135 S %C=$V(%I,%J)#256 Q:%C>127  S %RNAM=%RNAM_$C(%C)
        W ?5,%J,?19,$V(146,%J)#256,?33,%RNAM,! Q
PROQ    W !,"DO YOU WISH TO PROCEED WITH THE BACKUP" Q
PROQH   W !,"TYPE 'N' IF YOU DO NOT WISH TO PROCEED.  THEN YOU WILL BE ABLE "
        W "TO TAKE",!
        W "SOME CORRECTIVE ACTION, SUCH AS ASKING USERS TO LOG OFF, OR "
        W "LOGGING THEM",!
        W "OFF BY MEANS OF THE  ^RJD  UTILITY.",!
        W "BUT IT IS OK TO LEAVE THEM LOGGED IN - THEY WILL SIMPLY BE HUNG "
        W "UNTIL IT",!
        W "IS OK FOR THEM TO ACCESS THE DATABASE.",! Q
