BACKONE Q  ;DSM11 UTILITIES; COPYRIGHT 1980 DEC ;CALLED BY ^BACKSET
B1      S $ZT="E",MO=16777216 V ST::SA
        I FM S D=FD_FU,L=FRL,MA=1,B=FB_":"_""""_FD_FU_"""",S=FS,DE=FDE,FM=-1 D MNT
        S B=TB_":"_""""_TD_TU_"""" I TR S D=TD_TU,L=TRL,MA=0,S=TS,DE=TDE,TR=-1 D MNT
        I $D(UNATTN) S DMSG="BEGIN UNATTENDED BACKUP (BACKUP-COMMAND-FILE: "_NM_")" D HD^BACKUNJR G ST
        D WRTTI W "BEGIN BACKUP # ",N,!
ST      U 63:(1:1:"Z"),0 V TB:TD_TU S TE=$V(812,0)*400+TB
        U 63:(2:1:"Z") V FB:FD_FU S FE=$S($V(916,0):$V(916,0),1:$V(812,0))*400+FB
        S I1=906,SZ=4 D GTF S VSN=$E(M,2,SZ+1)
        U 63:(1:2),0 F I=496,498,712:2:811,904:2:983 V I:0:$V(I+1024,0)
        S MBS=$E(VSN,4)=1&($V(913,0)=1)&'IU&TBMAX G:'MBS LWRT
        S PTM=$V(904,0) U 63:(2:1:"C"),0 V -MO:TD_TU
        U 63:(1:2),0 S TMP=TE-TB\400,FMP=FE-FB\400
        F U=914:4 V U:0:TT*H+TCOD S FMP=FMP-TMP V U+2:0:TMP I FMP'>0 V U+2:0:TMP+FMP Q
        V 912:0:U-914\4+1*H+($V(912,0)#256)
        F U=U+4:2:944 V U:0:0
LWRT    V 8:0:$V(8,0)#256+($V(9+1024,0)*H) U 63:(1:1:"Z"),0 S S=0,T=TB D WLBA
        S F=FB+1,T=TB+1 G IU:IU
ALL     S P=BF,C=FE D C
BDON    D DKFIN:TB+1<T
        I $D(UNATTN) S DMSG="UNATTENDED BACKUP COMPLETE (BACKUP-COMMAND-FILE: "_NM_")" D HD^BACKUNJR G RET
        D WRTTI W "BACKUP # ",N," COMPLETE",! G RET
IU      S J=FB,W=2
NXMAP   U 63:(BF:1) V J+399:FD_FU I T'<TE D NXTDK G NXMAP
RA      I '$D(UNATTN) U 0 R *A:0 I  G RA:A'=27 D ESC
        V -T:TD_TU S T=T+1 I $V(1008,0)=21845,$V(1010,0)=43690,$V(1022,0)=399 G NX2
ALMAP   S C=J+399,P=BF D C
NX2     S J=J+400,F=J,W=0 G NXMAP:F<FE,BDON
C       I '$D(UNATTN) U 0 R *A:0 I  G C:A'=27 D ESC
        I F+P'>C U 63:(1:P) V F:FD_FU U 0 S F=F+P G PT:T+P>TE V:T -T:TD_TU V:'T -MO:TD_TU S T=T+P G C
        S P=C-F G C:P Q
PT      S S=TE-T,F=F-P+S I S U 63:(1:S),0 V:T -T:TD_TU V:'T -MO:TD_TU
        D NXTDK G C
NXTDK   D DKFIN,NXT S S=0 D WLB Q
DKFIN   S S=VL,VL=S+1 D WLB S T=TB,T=T+'MBS
        Q
COR     G:$D(UNATTN) ERROR1^BACKMM
        I MA'<0  W !,"( ENTER ""^"" IF YOU DO NOT WISH TO PROCEED WITH THE BACKUP)",!!
        W "PLEASE MOUNT THE CORRECT DISK" D MN2 G BBT
MNT     G:$D(UNATTN) ERROR1^BACKMM U 0 W !,"PLEASE DISMOUNT VOLUME SET DISK ",L," FROM DRIVE ",D
        W ", AND MOUNT",! G M2:'MA
        W "MASTER DISK ",FL G M3
M2      W "THE DISK THAT WILL HOLD THE BACKED UP INFORMATION" G M3
REMN    G:$D(UNATTN) ERROR1^BACKMM W !,"PLEASE RE-MOUNT VOLUME SET MASTER DISK ",L
M3      W " IN DRIVE ",D,!
        W "  *WRITE-" W:MA<1 "ENABLED*" W:MA=1 "PROTECTED*" D MN2 G BBT
MN2     I '$D(UNATTN) R !,"THEN TYPE  <CR>   ",A,! G FAKER:A="^" I A'="" G COR
        U 63:(1:1:"Z"),0 S A=$ZT,$ZT="DE" V @B S $ZT=A U 63:(::"C"),0
        S I1=882,SZ=8 D GTF I M'["DSM11 V3" G:$D(UNATTN) ERROR2^BACKMM W "NOT A DSM11 V3 DISK!" G COR
        S I1=816,SZ=22 D GTF G MA:$V(814,0)#H=$A("M"),NMA:MA
        G:$D(UNATTN) BBTA W !,"BACKUP LABEL IS: ",M
        S A=$V(880,0)#H,I1=838 D GTF G OKB:$L(M)<3!'A
        W !,"  IT IS BACKUP VOL # ",A," OF ",$C($V(878,0)#H,$V(879,0))
        W " MASTER ",M S I1=869,SZ=9 D GTF W ", CREATED ",$E(M,2,10)
OKB     R !!,"- OK TO USE THIS DISK [Y/N] ?  > ",A,!
        G BBTA:A="Y",OKB:A'="N",COR
        G BBTA
NMA     G:$D(UNATTN) ERROR3^BACKMM W "NOT A MASTER DISK! - HAS BACKUP" G M4
M4A     W " DISK! - HAS MASTER"
M4      W " LABEL: ",M G COR
MA      I 'MA!(M'=FL) G:$D(UNATTN) ERROR4^BACKMM
        I 'MA W "NOT A BACKUP" G M4A
        I M'=FL W "WRONG" G M4A
BBTA    Q
BBT     V DE::$V(DE)#16384+16384
        I MA<0 S I1=906,SZ=3 D GTF V DE::$V(DE)#16384+(16384*(M?1P3U1P+2))
        S MMS=$V(DE)\256#64+$V($V(44)+86)
        F I=0:2:190 V I:MMS:$V(512+I,0)
        Q
GTF     S M="""" F I=I1:1:I1+SZ-1 Q:$V(I,0)#256=0  S M=M_$C($V(I,0)#128)
        S M=M_"""" Q
FAKER   S E=1,$ZT="RET",=
DE      S A="READ" G DE2
DEW     V V::W0 S A="REWRITE BACKUP"
DE2     U 0 G E2:$ZE'?1"<DK".E G:$D(UNATTN) ERROR10^BACKMM W !,$E($ZE,1,7),!,"  WHILE TRYING TO ",A
        W " LABEL -" S E=2 G OVER
E       G E2:$ZE'?1"<DK".E S A="WRIT",B=T_":"_""""_TD_TU_"""" S:$I=63 A="READ",B=F_":"_""""_FD_FU_""""
        G:$D(UNATTN) ERROR11^BACKMM U 0 W !,"! ERROR: ",$ZE,!,A,"ING NEAR BLK # ",B S E=5 G OVER
E2      G:$D(UNATTN) ERROR7^BACKMM U 0 W !,"ERROR: ",$ZE S E=3
OVER    W !,"MUST TRY AGAIN FROM THE BEGINNING.",!
RET     S $ZT="E"
RT1     S MA=-1 U 63:(1:1),0
        I FM<0 S (L,FL)=FRL,D=FD_FU,B=FB_":"_""""_FD_FU_"""",S=FS,DE=FDE D REMN
        I TR<0 S (L,FL)=TRL,D=TD_TU,B=TB_":"_""""_TD_TU_"""",S=TS,DE=TDE D REMN
        V ST::64+2048+8192
        G BACFAIL^BACKUPDO:E,BACNEXT^BACKUPDO
WLB     U 63:(1:1:"Z"),0 V TB:TD_TU
WLBA    S L=$E(FL,2,$L(FL)-1) S:$L(L)<22 L=L_$C(0)
        F I=0:2:$L(L) V 838+I:0:$A(L,I+2)*H+$A(L,I+1)
        I S>1 F I=908:2:944 V I:0:0
        V 878:0:$A(FD,2)*H+$A(FD),880:0:IU*H+S,902:0:FE-FB\400
        V 814:0:MBS*H+($V(814,0)#256)
        V 868:0:$V(868,0)#H+($A(DA)*H) F I=2:2:9 V 868+I:0:$A(DA,I+1)*H+$A(DA,I)
        I MBS V 904:0:PTM,906:0:$A(VSN,2)*H+$A(VSN,1),908:0:$A(S)*H+$A(VSN,3),916:0:T-TB+399\400
        V V::W0+2 S $ZT="DEW" V -MO:TD_TU S $ZT="E" V V::W0 U 63:(::"C"),0 Q
NXT     G:$D(UNATTN) ERROR12^BACKMM W !,"OUT OF SPACE ON BACKUP DISK.  PLEASE MOUNT BACKUP DISK # ",VL
        S D=TD_TU,MA=0,B=TB_":"_""""_TD_TU_"""",S=TS,DE=TDE G M3
WRTTI   S TI=$P($H,",",2),T1=TI\3600,T2=TI#3600\60,TI=TI#60
        S:T2<10 T2=0_T2 S:TI<10 TI=0_TI W !,"**",$J(T1_":"_T2_":"_TI,9),"   "
        K T1,T2,TI Q
ESC     W !,?2,F-FB," BLKS PROCESSED SO FAR,  ",FE-F," TO GO.",!!
ES2     R "TYPE  <CR>  TO CONTINUE,",!,?7,"^    TO TERMINATE  : ",A,!
        Q:A=""  G ES2:A'="^",FAKER
