BACKVERI        Q  ;DSM11 UTILITIES; COPYRIGHT 1980 DEC
DKVER   ;
        S %FAIL=1 Q:'$D(^SYS(0,"BACKUP",NM,"DISK "_DK,"MODE"))
        Q:'$D(^("TO"))
        Q:'$D(^("FROM","UNIT"))  S D=^("UNIT") Q:'$D(^("MASTER LABEL"))
        G BTAP:^SYS(0,"BACKUP",NM,"DISK "_DK,"TO")="M"
        Q:'$D(^("VERIFY"))
        Q:'$D(^("TO","UNIT"))  S T=^("UNIT") G VERET
BTAP    Q:'$D(^("TO","MAGTAPE DENSITY"))
        Q:'$D(^("MAGTAPE BLOCK FACTOR"))
        Q:'$D(^("MAGTAPE UNIT"))
        G MTGOT:UU'<0 S U=$P(^("MAGTAPE UNIT"),";",1),MTCNT=1
        I ID=""&(U'=0) S %FAIL=-1 Q
        I $V($V($V(44)+8)+47+U)#256=255 S %FAIL=-1 Q
        S UU=U+47 C UU
MWHO    S OWN=$V($V($V(44)+8)+UU)#256
        I OWN=0 O UU::2 G MTGOT:$T,MWHO
        G OWNJ:OWN=$V($V(44)+55)
        I $D(UNATTN) D MESSG1,HD^BACKUP S %FAIL=4 Q
        W !!,"MAGTAPE UNIT ",U," IS OWNED BY JOB # ",OWN\2,"."
STOP    W !," -- CANNOT PROCEED.",! S %FAIL=4 Q
OWNJ    G MTGOT:JOP=3
        I $D(UNATTN) D MESSG2,HD^BACKUP S %FAIL=4 Q
        W !!,"MAGTAPE UNIT ",U," IS OWNED BY THE JOURNAL.  YOU CANNOT USE "
        W "THE SAME",!,"MAGTAPE UNIT FOR JOURNAL & BACKUPS UNLESS YOU HAVE "
        W "CHOSEN JOURNAL OPTION ""3""",!,"WHEN CREATING THE BACKUP COMMAND "
        W "FILE." G STOP
MTGOT   S T=""
VERET   S %FAIL=0,FM(DK)=0,I1=816,SZ=22 G NOTB:ID'="" S DIF=1
        U 63:(::"Z") V 0:SYU U 63:(::"C"),0 D GTF^BACKONE
        G SYBAS:D'=SYU
        Q:^SYS(0,"BACKUP",NM,"DISK "_DK,"FROM","MASTER LABEL")=M
SYBAS   G SYBAS^BACKCRG
NOTB    S DD=$E(D,1,2),U=$E(D,3) D RES Q:%FAIL
        I T'="" S DD=$E(T,1,2),U=$E(T,3) D RES
        Q
RES     S TY=$F(TYPES,DD)\3-1,DTE=$V($V(44)+224)+(TY*8+U*4)
        I $D(UNATTN) I '($V(DTE)#256) D MESSG3,HD^BACKUP S %FAIL=2 Q
        I '($V(DTE)#256) W !,"YOUR HARDWARE CONFIGURATION DOES NOT CONTAIN A DISK """,DD,U,""".",!
        I  S %FAIL=2 Q
        S MOU=$V(DTE)\16384 G NRES:MOU<2
        S:'DIF DIF=1 I DD_U'=D S DIF=-1 Q
        U 63:(::"Z") V 0:DD_U U 63:(::"C"),0 D GTF^BACKONE
        Q:^SYS(0,"BACKUP",NM,"DISK "_DK,"FROM","MASTER LABEL")=M
        S DIF=-1,FM(DK)=1 Q
NRES    Q:MOU=0  I $D(UNATTN) D MESSG4,HD^BACKUP S %FAIL=3 Q
        W !!,"** YOU MUST TYPE  ""D ^DISMOUNT""  TO DISMOUNT THE "
        W "DISK CURRENTLY IN",!
        W "DRIVE ",DD,U,", BEFORE PROCEEDING.",! S %FAIL=3
        Q
MESSG1  S MSG="MAGTAPE UNIT "_U_" IS OWNED BY JOB # "_(OWN\2)_".  UNATTENDED BACKUP ABORTED" Q
MESSG2  S MSG="MAGTAPE UNIT "_U_" IS OWNED BY THE JOURNAL.  UNATTENDED BACKUP ABORTED" Q
MESSG3  S MSG="HARDWARE CONFIGURATION DOES NOT CONTAIN A DISK """_DD_U_""".  UNATTENDED BACKUP ABORTED" Q
MESSG4  S MSG="THE DISK CURRENTLY IN DRIVE "_DD_U_" NOT DISMOUNTED.  UNATTENDED BACKUP ABORTED" Q
