BACKFL  ;YZH;30-SEP-83;MAINTAIN SCHEDULED BACKUP FILES
START   U 0 W !!,"SPECIFY ONE OF THE FOLLOWING:"
        W !,"1. INSPECT/MODIFY BACKUP SCHEDULE"
        W !,"2. PRINT SCHEDULED BACKUP ERROR REPORT"
        R !,"ENTER THE NUMBER OF YOUR CHOICE > ",OPT I OPT=""!(OPT="^") K OPT W !! Q
        I OPT=2 D ^BACKPRT G START
        I OPT'=1 D HLP1 G START
        I '$D(^SYS(0,"UNATTENDED BACKUP TIME")) D MESSG G START
        I ^("UNATTENDED BACKUP TIME")="" D MESSG G START
        W !!!!?3,"THE FOLLOWING BACKUP COMMAND FILE(S) HAVE BEEN SCHEDULED TO RUN:" D WRT
        W !!?5,"JOB NUMBER",?20,"COMMAND FILE NAME",?41,"SCHEDULED DATE AND TIME",!!
        F I=1:1 S DATIM=$P(^SYS(0,"UNATTENDED BACKUP TIME"),";",I) Q:DATIM=""  D SHOW
        D WRT W !!!
ASKM    R !!,"MODIFY BACKUP SCHEDULE FOR WHICH JOB NUMBER ? > ",JNUM I JNUM=""!(JNUM="^") G START
        I JNUM'?1N.N!(JNUM<1)!(JNUM'<I) D HLP2 G ASKM
ASKD    W !!,"DO YOU WISH TO REMOVE BACKUP JOB NUMBER ",JNUM R " ? <N> ",DOPT
        S:DOPT="" DOPT="N" G:DOPT="^" ASKM
        I DOPT?1"N".E G ST
        I DOPT'?1"Y".E D HLP3 G ASKD
        R !,"ARE YOU SURE ? <N> ",DOPT G:DOPT'?1"Y".E ASKD
        D DEL W !! G START
ST      W !!!,"MODIFY BACKUP SCHEDULE",!
FILNAM  S COMFL=$P(^SYS(0,"UNATTENDED BACKUP FILE"),";",JNUM)
        W !,"COMMAND FILE NAME <",COMFL R "> ",FILNM S:FILNM="" FILNM=COMFL
        G:FILNM="^" ASKM I '$D(^SYS(0,"BACKUP",FILNM)) D HLP4 G FILNAM
        S DATIM=$P(^SYS(0,"UNATTENDED BACKUP TIME"),";",JNUM)
DATE    S %DT=$P(DATIM,",",1) D %CDS^%H
        W !,"BACKUP STARTING DATE <",%DAT1 R "> ",%DT S:%DT="" %DT=%DAT1
        D %CDN^%H I '$D(%DAT) G DATE
TIME    S %TM=$P(DATIM,",",2) D %CTS^%H
        W !,"BACKUP STARTING TIME <",%TIM R "> ",%TM S:%TM="" %TM=%TIM
        D %CTN^%H I '$D(%TIM) G TIME
        D DEL S TIMFL=^SYS(0,"UNATTENDED BACKUP TIME")
        F I=1:1 S DATIM=$P(TIMFL,";",I) Q:DATIM=""!($P(DATIM,",",1)>%DAT)  I $P(DATIM,",",1)=%DAT Q:$P(DATIM,",",2)'<%TIM
        S ^("UNATTENDED BACKUP TIME")=$P(^("UNATTENDED BACKUP TIME"),";",1,I-1)_$S(I-1:";",1:"")_%DAT_","_%TIM_";"_$P(^("UNATTENDEDBACKUP TIME"),";",I,999)
        S ^("UNATTENDED BACKUP FILE")=$P(^("UNATTENDED BACKUP FILE"),";",1,I-1)_$S(I-1:";",1:"")_FILNM_";"_$P(^("UNATTENDED BACKUP FILE"),";",I,999)
        W !! G START
SHOW    S %DT=$P(DATIM,",",1) D %CDS^%H
        S %TM=$P(DATIM,",",2) D %CTS^%H
        W !?9,$J(I,2),?26,$P(^("UNATTENDED BACKUP FILE"),";",I),?45,%DAT1,?55,%TIM,! Q
DEL     S ^SYS(0,"UNATTENDED BACKUP TIME")=$P(^SYS(0,"UNATTENDED BACKUP TIME"),";",1,JNUM-1)_$S(JNUM-1:";",1:"")_$P(^("UNATTENDED BACKUP TIME"),";",JNUM+1,999)
        S ^("UNATTENDED BACKUP FILE")=$P(^("UNATTENDED BACKUP FILE"),";",1,JNUM-1)_$S(JNUM-1:";",1:"")_$P(^("UNATTENDED BACKUP FILE"),";",JNUM+1,999)
        Q
WRT     W !?3 F J=1:1:64 W "-"
        Q
MESSG   W !!,"*** NO BACKUP JOB HAS BEEN SCHEDULED.",! Q
HLP1    W !!,"ENTER '1' IF YOU WANT TO INSPECT OR MODIFY THE BACKUP JOB(S)"
        W !,"WHICH HAVE BEEN SCHEDULED TO RUN"
        W !!,"ENTER '2' IF YOU WANT TO PRINT ERROR REPORT FOR THE SCHEDULED"
        W !,"BACKUP JOB(S) WHICH HAVE BEEN EXECUTED",! Q
HLP2    W !!,"ENTER THE JOB NUMBER FOR WHICH YOU WANT TO MODIFY"
        W !,"THE BACKUP SCHEDULE",! Q
HLP3    W !!,"ENTER Y(ES) OR N(O)",! Q
HLP4    W !!,"YOU MUST ENTER AN EXISTING BACKUP-COMMAND-FILE-NAME"
        W !,"OR  ENTER <CR> TO ACCEPT DEFAULT",! Q
