BACKMNT ;DSM11 UTILITIES; COPYRIGHT 1980 DEC
        Q
MNTIF   ;
        S D=FD_FU G FMNT:'FR U 63:(1:1:"Z"),0 V FB:FD_FU U 63:(::"C"),0
        G FMA:$V(814,0)#H=$A("M")
NMAS    D RMSG G:$D(UNATTN) ERROR1 W " DOES NOT HAVE A MASTER LABEL !"
NM2     W !,"  -- BACKUP TERMINATED." S E=-2 G FAIL
FMA     S I1=816,SZ=22 D GTF^BACKONE S FRL=M
        I 'FM G OKMAS:FL=M D RMSG G:$D(UNATTN) ERROR2 W "HAS MASTER LABEL:",!,M,"." G NM2
        I $D(UNATTN) D RMSG G ERROR2
        G OKMAS:FL'=M D RMSG W " *HAS* MASTER LABEL:",!,M
        W ".  -- IT SHOULDN'T !" G NM2
FMNT    S L=FL,T=FT,MA=1,B=FB_":"_""""_FD_FU_"""",DE=FDE D MNT G MNTERR:E
OKMAS   ;
        I ME D MAGSET^BACKMM G FAIL:E,GO
        S D=TD_TU G RMNT:'TR U 63:(1:1:"Z"),0 V TB:TD_TU U 63:(::"C"),0 G NMAS:$V(814,0)#H'=$A("M")
        S I1=816,SZ=22 D GTF^BACKONE S TRL=M G GO
RMNT    S L="",T=TT,MA=0,B=TB_":"_""""_TD_TU_"""",DE=TDE D MNT G MNTERR:E
GO      K DDU,%A,ANS,L,DEF,%YN,QMK,QUES
        I ME G M1^BACKMMGO
        G B1^BACKONE
FAIL    G BACFAIL^BACKUPDO
MNTERR  Q
MNT     V DE::$V(DE)#16384+16384,DE+2::0 G:$D(UNATTN) MNTC
        W !,"PLEASE MOUNT " G MNT2:L=""
        W "MASTER DISK ",L,!
        W "  IN DRIVE ",D,"  *WRITE-PROTECTED*" G MNTC
MNT2    I '$D(UNATTN) W "DISK THAT WILL HOLD THE BACKED UP INFORMATION",!
        I  W "  IN DRIVE ",D,"  *WRITE-ENABLED*"
MNTC    D MN2^BACKONE Q:E
MNTBB   V DE+2::$V(812,0)
        D BBT^BACKONE Q
RMSG    S MSG="! THE RESIDENT MASTER DISK IN DRIVE "_D W:'$D(UNATTN) !,MSG Q
ERROR1  S MSG=MSG_" DOES NOT HAVE A MASTER LABEL !  UNATTENDED BACKUP ABORTED" G SETR
ERROR2  S MSG=MSG_" HAS MASTER LABEL: "_M_".  UNATTENDED BACKUP ABORTED" G SETR
ERROR3  S MSG=MSG_" *HAS* MASTER LABEL: "_M_".  -- IT SHOULDN'T !  UNATTENDED BACKUP ABORTED"
SETR    D HD^BACKUP G FAIL
