BACKJRN Q  ;DSM11 UTILITIES; COPYRIGHT 1980 DEC
ASKJRN  S SUB="0,BACKUP,'NM,JOURNAL QUESTION/N" D DEF^SYSROU
        S QUES="JQUES" X ^%Q("ASKYN") Q:%A  S @SYV=ANS
        I ANS="N" S ^("JOURNAL OPTION")=0 G KRET
MIGHT   S SUB="0,BACKUP,'NM,JOURNAL OPTION/1" D DEF^SYSROU S QUES="IFQ"
        S:DEF=0 DEF=1
MI2     X ^%Q("EN") G ASKJRN:%A I ANS'?1N!("123"'[ANS) D IV S QUES="IFQ2" G MI2
        S @SYV=ANS G KRET:ANS=1
FRESH   S SUB="0,BACKUP,'NM,JOURNAL SPACE SAME/Y" D DEF^SYSROU
FR2     S QUES="LOCQ" X ^%Q("ASKYN") G MIGHT:%A,CANT:ANS="N" S @SYV=ANS
        Q
KRET    K ^SYS(0,"BACKUP",NM,"JOURNAL SPACE SAME")
        Q
IV      W !,"INCORRECT RESPONSE - ENTER '?' FOR MORE INFORMATION.",! Q
JQUES   W !,"WILL JOURNALING BE RUNNING WHEN YOU RUN "
        W !,"THIS BACKUP COMMAND FILE" Q
JQUESH  W !,"ANSWER 'N' IF JOURNALING IS NOT IN THE CONFIGURATION THAT WILL "
        W "BE RUNNING",!
        W "AT THE TIME YOU EXECUTE THIS BACKUP COMMAND FILE, OR IF JOURNALING"
        W " IS IN",!
        W "THAT CONFIGURATION, BUT WILL NOT BE RUNNING AT THAT TIME.",!!
        W "ANSWER 'Y' IF JOURNALING WILL BE RUNNING, OR *MIGHT* BE RUNNING, "
        W "AT THAT TIME.",!! Q
IFQ     W !,"ASSUMING JOURNALING IS RUNNING AT THAT TIME, WILL YOU WISH TO:",!
        W " 1. LET JOURNALING CONTINUE NORMALLY,",!
        W " 2. UPON SUCCESSFUL COMPLETION OF THE BACKUP(S) START A FRESH "
        W "JOURNAL (BUT",!
        W "    IF THE BACKUPS DO NOT COMPLETE SUCCESSFULLY, SIMPLY CONTINUE "
        W "THE",!,"    PRESENT JOURNAL), OR",!
        W " 3. STOP THE JOURNAL UNCONDITIONALLY JUST BEFORE THE BACKUPS "
        W "BEGIN, AND START",!
        W "    A FRESH JOURNAL UPON COMPLETION, WHETHER THE BACKUPS WERE "
        W "SUCCESSFUL",!,"    OR NOT.",!!
IFQ2    W "ENTER OPTION (OR '?') " Q
IFQ2H   ;
IFQH    W !,"NORMALLY YOU WILL CHOOSE OPTION 1.  JOURNALING, AND ALL JOBS "
        W "THAT ATTEMPT",!
        W "TO JOURNAL, WILL BE SUSPENDED BEFORE THE BACKUP BEGINS.  UPON "
        W "TERMINATION",!
        W "OF THE BACKUP(S), WHETHER THEY WERE SUCCESSFUL OR NOT, JOURNALING "
        W "WILL BE",!
        W "RESUMED EXACTLY WHERE IT LEFT OFF.",!!
        W "OPTION 2 WORKS AS FOLLOWS: JOURNALING IS SUSPENDED, AS ABOVE, AT "
        W "THE",!
        W "BEGINNING OF THE BACKUP(S).  WHEN ALL THE BACKUPS HAVE COMPLETED "
        W "SUCCESSFULLY,",!
        W "A NEW JOURNAL IS STARTED (WHICH WILL THEREFORE CONTAIN A RECORD OF "
        W "CHANGES",!
        W "MADE TO THE DATABASE AFTER THIS BACKUP).  IF THE BACKUPS DO NOT "
        W "COMPLETE",!
        W "SUCCESSFULLY, THE OLD JOURNAL IS SIMPLY RESUMED WHERE IT LEFT OFF."
        W !!,"OPTION 3 *MUST* BE CHOSEN IN THE FOLLOWING INSTANCE: YOU ARE "
        W "JOURNALING TO",!
        W "A MAGTAPE UNIT BEFORE THE BACKUP BEGINS.  BUT YOU WILL BE USING "
        W "THAT SAME",!
        W "MAGTAPE UNIT FOR ONE OR MORE OF THE BACKUPS.  IN THIS CASE, "
        W "JOURNALING",!
        W "*MUST* BE STOPPED (BY CHOOSING OPTION 3) BEFORE THE BACKUPS CAN "
        W "BEGIN, AND",!
        W "A FRESH JOURNAL STARTED UPON COMPLETION, WHETHER SUCCESSFUL OR "
        W "NOT.",!!!
        Q
LOCQ    W !,"SHOULD THIS FRESH JOURNAL SPACE START AT THE BEGINNING OF THE "
        W "SAME MAGTAPE",!
        W "UNIT (OR JOURNAL DISK-SPACE REGION) THAT WAS BEING USED FOR "
        W "JOURNALING JUST",!
        W "BEFORE THE BACKUPS BEGAN" Q
LOCQH   W "It is expected that you will answer 'Y'.  The Journal will "
        W "automatically",!
        W "be started at the beginning of the same magtape unit or disk-"
        W "space",!
        W "region that was in use just prior to the Backup.  (But the "
        W "operator *will*",!
        W "be given an opportunity to change tapes if the device was magtape.)"
        W !,"If you answer 'N', you will be given further Help-text.",!
        Q
CANT    W !,"If you wish to change Magtape unit # or disk-space region, you "
        W "will have to",!
        W "manually shut down Journaling before the Backup, and re-start it "
        W "afterward.",!
        G ASKJRN
