BSCPER  ;30-Aug-82 ;UTILITY ;BSC ;INITIALIZES ERROR MASKS FOR BSC PE ;JHM
        S %SACK="LOZ#2"
        S %SCOV="LOZ\2#2"
        S %SRVI="LOZ\4#2"
        S %STPR="LOZ\8#2"
        S %SDEV="%SEL=LOZ\256#256"
        S %ECNTN="HIZ#2"
        S %EFRMT="HIZ\2#2"
        S %ENAKX="HIZ\4#2"
        S %ENOTM="HIZ\8#2"
        S %EENQX="HIZ\16#2"
        S %EOVER="HIZ\32#2"
        S %EABOR="HIZ\64#2"
        S %EDISC="HIZ\128#2"
        S %ETIMO="HIZ\256#2"
        S %ENDSR="HIZ\512#2"
        S %ENCXR="HIZ\1024#2"
        S %ENCTS="HIZ\2048#2"
        Q
