BSCRCV  ;31-Aug-82 ;UTILITY ;BSC ;2780/3780 PE DATA RECEIVER ;JHM
STRT    D CHKHLT G SHTDWN^BSCPEB:'$T
        ZA @%GIN S (%FN,@%GIN)=@%GIN+1 ZD @%GIN
        S %AP=%GSUB_%FN_")",%MSN=16
        S %RN=0,^BSCDAT(%DEV)="RECEIVING "_%AP D SNDMES^BSCPEB
        D GETZA S @("%TPR="_%STPR) I %TPR S %SEL="PUNCH",%P="TRANSPARENT" G STRCV
        S @%SDEV,%P="NONTRANSPARENT" S:%NMOD="P" %SEL=%REC
        I %EMUL S %SEL=$S(%SEL=18:"PUNCH",%SEL=19:"PUNCH",%SEL=17:"PRINTER",1:"UNKNOWN")
        E  S:%SEL=27 %SEL=$E(%REC,2) S %SEL=$S(%SEL=4:"PUNCH",%SEL=3:"PRINTER",1:"UNKNOWN")
        S %REC=$E(%REC,2+'%EMUL*(%SEL'="UNKNOWN")*(%NMOD="P"),$L(%REC))
STRCV   S @(%GSUB_%FN_")")=%P_" "_%SEL S %LN=%REC G PCREC
RDREC   U %DEV R %LN I $ZA<0 D ABRFIL G RCVERR
PCREC   I '%TPR S %LN=$P(%LN,$C(25),1)
        D PUTREC G RDREC:$ZB#256'=3
        D ENDFIL U %DEV R %REC:20 G STRT:$ZA'<0
RCVERR  D GETZA I @%EABOR S ^BSCDAT(%DEV)="IDLE" G CHKFIL^BSCPEB
        G DISCON^BSCPEB
PUTREC  S @(%GSUB_%FN_","_%RN_")")=%LN,%RN=%RN+1 Q
GETZA   U %DEV S HIZ=$ZA\65536,LOZ=$ZA#65536 Q
CHKHLT  ZA ^BSCDAT(%DEV):10 ZD ^BSCDAT(%DEV) Q
ENDFIL  S %Q="RCVD",%MSN=6 G SAVTRN
ABRFIL  S %Q="ERROR",%MSN=10
SAVTRN  S %AP=%GSUB_%FN_")"
        S ^BSCDAT(%DEV,%Q,%FN)=%DAT1_" "_%TIM1_" "_%AP D SNDMES^BSCPEB
        S ^BSCDAT(%DEV,%Q)=^BSCDAT(%DEV,%Q)+1 Q
