DDP     ;27-Feb-85 ;UTILITY ;DDP ;DDP UTILITY MENU ;JHM
        D CHKSYS^SYSROU Q:%A  D:$D(^UTILITY("MENU",$J,"MENU")) PUSH^%MENU S ^UTILITY("MENU",$J,"MENU")="^%MENU(""SYS"",""DDP"")" D %
STT^%MENU
        S %NOPAUSE=1 Q
