DESPOOL Q  ;DEFAULT DESPOOLER 17-JUL-80
        W !,"Unavailable for Field Test Phase 1",! Q
START   I ^SYS(0,"STARTUP","DESPOOLER")="N" H 1 G START
        S D=$V($V($V(44)+230)) O D
CHECK   G:(^SYS(0,"STARTUP","DESPOOLER")="N") QUIT O 2:D+512 I $ZA<0 H 5 G CHECK
        S ZAM=$ZA#256,^("DESPOOLER FILE")=ZAM U D W !!!!,"SPOOL FILE # ",ZAM,"  PRINTED   " D ^%D W "   " D ^%T W !!,#
PRINT   U 2 R X G:$ZA<0 DONE U D W X G PRINT:^SYS(0,"STARTUP","DESPOOLER")'="N",QUIT
DONE    S ^("DESPOOLER FILE")="" U D W *12 C 2:256 G CHECK
QUIT    H
