JRNSTU  ; DSM11 Utilities ; Copyright 1980 DEC
        Q
JRNGO   S %ST=$V(44),JSN=^SYS(0,"STARTUP","JOURNAL SPACE NAME") G:JSN?1N TAPE
        S JSI=^("JOURNAL SPACE INIT") D NOMSG^JRNLSHOW
        F I=1:1:ND S %IX=ND(I) I ^SYS(0,"JOURNAL SPACE",%IX,"NAME")=JSN G JGOT
        W !," ** THERE IS NO JOURNAL-SPACE NAMED  '",JSN,"'  IN THE CURRENT ",!
        W "    CONFIGURATION."
EMSG    W !,*7,"    AFTER START-UP IS COMPLETE, TYPE:    D ^JRNL",!
        W "    IF YOU WISH TO START UP THE JOURNAL.",!,*7 G DONE
JGOT    S %JSP="JOURNAL SPACE"
        G:^("NEXT")="EMPTY" EMP I JSI="I" S INX=%IX D INIT^JRNINIT O 63 G EMP
        I ^("NEXT")="FULL" W !," ** JOURNAL SPACE  '",JSN,"'  IS FULL." G EMSG
        S %CR=^("NEXT")+(^("NEXT")#400=399) G SYSP
EMP     S %CR=^("START")
SYSP    D SYSPUT^JRNGETST
ONJRN   S %RUNJ=%ST+410,%START=2 D START^JRNSTART
DONE    K JSN,JSI,%JSP,%RUNJ,%MT,%DVM,ZA,%START
        Q
TAPE    G TOK1:^SYS(ID,"MT")>JSN
        W !," ** THERE IS NO MAGTAPE UNIT# ",JSN," IN THIS CONFIGURATION."
        G EMSG
TOK1    S %MT=47+JSN,%DVM=$V($V(44)+8)+%MT
        O %MT:"DS":3 G TFAIL:'$T U %MT S ZA=$ZA U 0
        I ZA\4#2!(ZA\64#2=0) C %MT G TFAIL
        D GIV^JRNSTART G ONJRN
TFAIL   W !," ** JOURNAL-TAPE (Unit# ",JSN,") IS WRITE-LOCKED, OFF-LINE, OR "
        W "UNAVAILABLE." G EMSG
