PATCH   ;8-Feb-85 ;UTILITIES ;AUTOPATCH UTILITIES ;Main menu driver ;JHM
        D:$D(^UTILITY("MENU",$J,"MENU")) PUSH^%MENU S ^UTILITY("MENU",$J,"MENU")="^%MENU(""SYS"",""SYSTEM ROUTINES (MISC.)"",""AUTOP
ATCH"")" D %STT^%MENU
        S %NOPAUSE=1 Q
