PCHIST1 Q  ; ROUTINE TO LOG HISTOGRAM
START   K (ST,HIST,SZ,MM,TAB,RANGE,START,CELLS,SUB,PAT,VEC,TIM,DIV,TIMS,CONF)
        F RUNS=1:1:TIMS S SUB=SUB+1 S ^HST=SUB D NEXT
        G EXIT
NEXT    F I=HIST:2:CELLS+HIST-2 V I:$J:0
        S STIME=$H
        S $ZT="ERROR" V PAT+10::0,PAT+12::0,VEC::PAT+14 H TIM*60
STORE   S ^HST(SUB,"CONF")=CONF
        S ETIME=$H V VEC::$V(PAT)
        F I=1:1:5 S ^HST(SUB,"MODULE",I)=$V(I*2+TAB-2)
        F I=6:1:12 S ^(I)=$V(ST+26)-128*64+$V(I*2+TAB-2)
        F I=13:1:19 S ^(I)=$V(ST+28)-128*64+$V(I*2+TAB-2)
        F I=20:1:28 S ^(I-2)=$V(I*2+TAB-2)*64
        S ^HST(SUB,"STIME")=STIME,^("ETIME")=ETIME,^("TOTAL")=$V(PAT+12)*65536+$V(PAT+10),^("DIV")=DIV
        S ^("START")=START,^("RANGE")=RANGE,^("CELLS")=CELLS
        F I=1:1:CELLS S ^HST(SUB,"CELLS",I)=$V(I+HIST-1,$J)#256
        I TIMS'=0,^HST'=0 Q
EXIT    S ^HST=0 H
ERROR   U 0 W !,"ERROR" S TIMS=0 G STORE
