PCHISTP W !,"PRINT PC HISTOGRAM FROM ^HST GLOBAL",!
WHICH   R !!,"WHICH HISTOGRAM ? ",SUB I SUB="^"!(SUB="") Q
        G:$D(^HST(SUB)) TABLE R " -- NO SUCH. DO YOU WISH A LIST ? ",SUB I SUB'="Y" G WHICH
        W !,"STRIKE ANY KEY WHEN YOU'VE SEEN ENOUGH...",! S SUB=-1
        F I=1:1 S SUB=$N(^HST(SUB)) G:SUB=-1 WHICH D ID R *X:0 I  G WHICH
TABLE   F I=1:1:27 S J=^HST(SUB,"MODULE",I) S A(J)=$P($T(ADDRESS),";;",I+1)
NEXT    S %DO=^HST(SUB,"START")*2 D ^%DO S DEF=%DO,TXT="STRTT" D OCT G:ANS="^" WHICH S %OD=ANS D ^%OD S START=%OD\2
NEXTR   S %DO=^HST(SUB,"START")+^("RANGE")*2 D ^%DO S DEF=%DO,TXT="ENDT" D OCT G:ANS="^" NEXT S %OD=ANS D ^%OD S RANGE=%OD/2-START
        W !?5,"THAT'S ",RANGE," (DECIMAL) PC ADDRESSES.",!
FORM    W !,"HOW MANY BUCKETS DO YOU WISH ON YOUR PRINTOUT <",RANGE\^("DIV"),"> "
        R BUCKS G:BUCKS="^" WHICH I BUCKS="" SET BUCKS=RANGE\^("DIV")
        I BUCKS>^("CELLS")!(BUCKS'?.N) W !?5,"BUCKETS MUST BE A NUMBER LESS THAN OR EQUAL TO ",RANGE\^("DIV") G FORM
        S RO=RANGE\^("DIV")/BUCKS D RO S NODES=RO
        S DIV=^("DIV"),STADD=^("START"),CELL=START-STADD\DIV,END=RANGE\^("DIV")+CELL
QUANT   W !,"HOW MANY HISTOGRAMS DO YOU WISH STARTING WITH ",SUB," <1> ? "
        R QT,! G:QT="^" WHICH S:QT="" QT=1 I QT'?.N W "NUMERALS PLEASE",! G QUANT
        F I=SUB:1:SUB+QT-1 I '$D(^HST(I)) W "CAN'T FIND HISTOGRAM #",I,! G QUANT
        S %DEF=3 D ^%IOS G:'$D(%IOD) WHICH W ! U %IOD
PRINT   D HEADING W !!?42,"PER CENT OF TOTAL ELAPSED TIME",! D LINE1,LINE2
        S NAME="",ADDR1=0,ADDR2=$N(A(ADDR1)),N=^("TOTAL")/1000,CELL=0
LINE    S BUCK=0 F I=1:1:NODES Q:'$D(^HST(SUB,"CELLS",CELL+I))  S BUCK=BUCK+^(CELL+I)
        I I=1,'$D(^(CELL+1)) G DONE
        S %DO=CELL*DIV+STADD*2
ADDR    I %DO'<ADDR2 S ADDR1=ADDR2,ADDR2=$N(A(ADDR2)) G ADDR
        I A(ADDR1)'=NAME W $J(A(ADDR1),6),"+" S NAME=A(ADDR1)
        S %DO=%DO-ADDR1 D ^%DO W ?7,$J(%DO,5)," |"
        S STARS=BUCK/N,STARS=$E($P(STARS,".",2),1)>4+$P(STARS,".",1)
        F I=1:1:STARS W "*" Q:I=100
        S STAR=STARS+5\5*5 F I=STAR:5:100 W ?I+13,"|"
        I STARS W " ",$J(STARS*.1,4,1),"%"
        W ! S CELL=CELL+NODES G DONE:CELL>END,LINE
HEADING W $C(12),!?32,"SYSTEM PERFORMANCE STATISTICS FOR ",$ZV,", ",^HST(SUB,"CONF"),!
ID      W !?16,"STATISTICS SESSION #",SUB," WAS LOGGED ON " S %DT=$P(^HST(SUB,"STIME"),",",1) D %CDS^%H W %DAT1
        S SECS=$P(^HST(SUB,"ETIME"),",",1)-$P(^("STIME"),",",1)*86400+$P(^("ETIME"),",",2)-$P(^("STIME"),",",2)
        S %TM=$P(^("STIME"),",",2) D %CTS^%H W " AT ",%TIM1," FOR AN ELAPSED TIME OF",$J(SECS/60,7,2)," MINUTES" Q
RO      S RO=$P(RO,".",2)'=""+$P(RO,".",1) Q
DONE    D LINE2,LINE1 S SUB=SUB+1,QT=QT-1 I QT G PRINT
        W $C(12) U 0 C:%IOD'=$I %IOD K %IOD G WHICH
OCT     W !,$P($T(@TXT)," ",2,80)," (OCTAL) " W:DEF "<",DEF R ">",ANS I ANS="" S ANS=DEF
        Q:ANS="^"  I ANS="?" D @(TXT_"H") G OCT
        I ANS'?.N!(ANS[8)!(ANS[9) W "  OCTAL DIGITS PLEASE." G OCT
        Q
STRTT   WHAT IS THE FIRST LOCATION YOU WISH TO PRINT
ENDTH   ;
STRTTH  W !,"ENTER THE OCTAL LOCATION",! Q
ENDT    WHAT IS THE LAST LOCATION YOU WISH TO PRINT
LINE1   W ?13,"0    .5   1   1.5   2   2.5   3   3.5   4   4.5   5   5.5   6   6.5   7   7.5   8   8.5   9   9.5   10",! Q
LINE2   W ?13,"|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|",! Q
ADDRESS ;;VECTOR;;SYSTAB;;EXEC;;MUMPS;;PATCH;;INTERP;;SUBRS;;EVAL;;SYMBOL;;GLOBAL;;ALLOC;;ZCALL;;KEXEC;;DISK;;EMT;;JRNL;;EBCDIC;;XDT;;DDBTAB;;KIOD;;MTD;;SPOOL;;SDP;;DMC;;JOBCOM;;DDP;;USRDRV
