PCHIST  ;UTILITY;PC HISTOGRAM;PERFORMANCE TEST
        K  S HIST=64*32,ST=$V(44),TAB=ST+92,SZ=$V(2*$J+$V(ST+6)),MM=SZ\16*16+(HIST\64)
        S SZ=SZ#16*2+1*512-(HIST+512) I SZ<512 W !,"PARTITION TOO SMALL, MUST BE AT LEAST ",HIST+1024," BYTES",! Q
        I SZ>8192 S SZ=8192
        W !!,"ROUTINE TO CREATE A PC HISTOGRAM"
VEC     S DEF=100,TXT="VECT" D OCT Q:ANS="^"
        S %OD=ANS D ^%OD S VEC=%OD I VEC>510 W "   THAT'S NOT LIKELY!",! G VEC
        I ANS=104 V 2::2,68::2,62818::97,62816::75
        S PAT=$V(ST+472)
NEXT    S %DO=$V(TAB+4) D ^%DO S DEF=%DO,TXT="STRTT" D OCT G:ANS="^" VEC S %OD=ANS D ^%OD S START=%OD\2
        S %DO=$V(TAB+56)*64 D ^%DO S DDP=%DO
        S %DO=$V(TAB+42)*64 D ^%DO S TTY=%DO
NEXTR   W !!,"(Default includes KIOD, specify ",DDP," to include all of kernel)"
        S DEF=TTY,TXT="ENDT" D OCT G:ANS="^" NEXT S %OD=ANS D ^%OD S RANGE=%OD\2-START
        W !?5,"THAT'S ",RANGE," (DECIMAL) PC ADDRESSES.",!
CELLS   W !,"HOW MANY HISTOGRAM CELLS (DECIMAL) <",SZ R "> ",CELLS
        I CELLS="" S CELLS=SZ
        G:CELLS="^" NEXTR
        I CELLS'?.N!(CELLS>SZ) W " -- A NUMBER UP TO ",SZ," PLEASE." G CELLS
        I CELLS>RANGE S CELLS=RANGE W !?5,"WE'LL REDUCE THAT TO ",CELLS
        S DIV=RANGE/CELLS I DIV["." S DIV=$P(DIV,".",1)+1
        W !?5,"THE HISTOGRAM WILL RECORD HITS FOR ",DIV," PC ADDRESS" W:DIV>1 "ES" W " PER CELL."
TIMS    W !,"HOW MANY LOGGING SESSIONS DO YOU WISH <1> ? " R TIMS I TIMS="" S TIMS=1
        I TIMS="^" G CELLS
        I TIMS'?.N!('TIMS) W !?5,"ENTER A POSITIVE INTEGER PLEASE.",! G TIMS
TIM     W !,"HOW LONG, IN MINUTES, DO YOU WISH EACH LOGGING SESSION TO LAST ? "
        R TIM,! I TIM="^" G TIMS
        I TIM'?1.3N!(TIM>100) W !?5,"ENTER ANY TIME INTERVAL UP TO 100 MINUTES.",! G TIM
        S SUB=0 F I=1:1 Q:$N(^HST(SUB))=-1  S SUB=$N(^HST(SUB))
        W !,"FIRST HISTOGRAM WILL BE FILED AS #",SUB+1
        W !,"WHAT IS YOUR SYSTEM CONFIGURATION NAME ? " R CONF I CONF="^" G TIM
READY   R !,"READY TO PROCEED <Y> ",ANS G:ANS="^"!(ANS="N") TIM I ANS'="",(ANS'="Y") G READY
        V PAT::$V(VEC),PAT+2::START,PAT+4::RANGE,PAT+6::DIV,PAT+8::MM
        W !!,"JOB #",$J," NOW DETACHING FROM TERMINAL AND RUNNING AS BACKGROUND JOB."
        W !,"NODE ^HST HOLDS IN-PROGRESS HISTOGRAM NUMBER, OR ZERO IF DONE."
        W !,"SET ^HST=0 TO SIGNAL THE HISTOGRAM LOGGER TO STOP AFTER ITS NEXT SESSION."
        W !,"Exit",! C $I G START^PCHIST1
OCT     W !,$P($T(@TXT)," ",2,80)," (OCTAL) " W:DEF "<",DEF R ">",ANS I ANS="" S ANS=DEF
        Q:ANS="^"  I ANS="?" D @(TXT_"H") G OCT
        I ANS'?.N!(ANS[8)!(ANS[9) W "  OCTAL DIGITS PLEASE." G OCT
        Q
VECT    ENTER CLOCK'S VECTOR
VECTH   W !,"KW11-L IS 100, KW11-P IS 104, KW11-K FLOATS",! Q
STRTT   WHAT IS THE FIRST LOCATION YOU WISH TO MONITOR
ENDTH   ;
STRTTH  W !,"ENTER THE OCTAL LOCATION; ADD 100000 IF IN KERNEL-ONLY AREA",! Q
ENDT    WHAT IS THE LAST LOCATION YOU WISH TO MONITOR
