RESTMNT Q  ;DSM11 UTILITIES; COPYRIGHT 1980 DEC
RSETUP  ;
        S $ZT="UNEX^RESTMNT",MM=$V(ST+86),SYE=$V(ST+56)#H\4*4+$V(ST+224)
        G MASMT:MAG
        S BFA=$V(ST+32)-4,DDU=XD_XU D SETBF
        S DDU=MD_MU D SETBF
        S:BFA>127 BFA=127 G BMNT:BFA<3 S BF=BFA
BFTRY   C 63 O 63:BF:2 E  G VLOST:BF=2 S BF=BF+1\2 G BFTRY
BMNT    I RESY=-1 G MASMT
        U 63:(1:1),0 S MA=0,DDU=XD_XU,DE=XDE,B=XB_":"_""""_XD_XU_"""" D MNTIT^RESTDO G TERM:%FAIL
        S XE=$V(812,0)*400+XB,MBS=$V(815,0)
        G BAMAS:MAS S BAL=M,V=$V(880,0)#H
        S MTY=$C($V(878,0)#128,$V(879,0)#128)
        S I1=869,SZ=9 D GTF^RESTDO S BDA=$E(M,2,10)
        S I1=838,SZ=22 D GTF^RESTDO
        W !,"BACKUP LABEL ON THIS DISK IS:  ",BAL,!
        I $L(M)<3 W !,"! THERE IS NO RECORD OF ANYTHING BACKED UP ON THIS "
        I  W "DISK !",! G BMNT
        W "  BACKUP (VOLUME # ",V,") OF ",MTY," MASTER:  ",M,"  CREATED ",BDA,!
        I 'MBS,MTY'=MD W !,"THIS IS A BACKUP OF A """,MTY,""" MASTER -- CANNOT "
        I  W "RESTORE TO A",!,"""",MD,""" MASTER.",! G STOP
        G MLOK:M=ML W "! YOUR PREVIOUS ANSWER INDICATED THAT THE MASTER TO BE "
        W "RESTORED HAD",!
        W "LABEL:  ",ML,!
        W "YOU HAVE MOUNTED THE INCORRECT BACKUP DISK.  IF THIS *IS* THE "
        W "CORRECT BACKUP",!
        W "DISK, THEN THE MASTER TO BE RESTORED TO MUST HAVE MASTER LABEL:",!
        W ML,!! G STOP
MLOK    ;
        I 'V W "! VOLUME NUMBER = 0  MEANS THE BACKUP WAS NOT COMPLETED "
        I  W "SUCCESSFULLY.",!," -- UNABLE TO PROCEED WITH THE RESTORE.",!
        I  G STOP
        I V>1 W "! YOU HAVE MOUNTED VOLUME NUMBER ",V," OF THE MULTI-VOLUME "
        I  W "BACKUP.",!,"PLEASE MOUNT VOLUME NUMBER 1.",! G BMNT
OK      S MAPS=$V(902,0),IU=$V(881,0),VL=1,MBS=$V(815,0)
        I ID="" S XS=3*256 V DE+2::$V(812,0),DE::$V(DE)+XS G LODB
        S TYP=XTYP
LODB    V DE+2::$V(812,0) S MMS=$V(DE)\256#64+$V($V(44)+86)
        F I=0:2:190 V I:MMS:$V(512+I,0)
MASMT   S MSAV=$V(MDE),MBB=$V(MDE+2)
        I RESY U 63:(2:1:"Z"),0 V:RESY>0 MB:MD_MU V:RESY<0 XB:XD_XU U 63:(::"C"),0
        I RESY S I1=816,SZ=22 D GTF^RESTDO S MSY=M
        S MA=1,DDU=MD_MU,DE=MDE,B=MB_":"_""""_MD_MU_""""
        I RESY'=1 D MASMOU^RESTMAS G STOP:%FAIL
        K KINDS,TYPES
        I MAG S P=BF-IU,MFS=FAC*1024 G RE^RESTDOMG
        G RE^RESTDO:RESY'<0,RE^RESTRESB
BAMAS   W !,"! BACKUP LABEL EXPECTED !",!
        W "THIS DISK HAS A MASTER LABEL:  ",M,! G STOP
TERM    U 0 W !!,"TERMINATED BY OPERATOR",! G FIN
VLOST   W !,"View buffer is now busy.",! G STOP
UNEX    U 0 W !,"! UNEXPECTED ERROR: "
        W $ZE,!
STOP    W " -- STOPPING.",!! G FIN
FIN     I UU'<47 U UU W *5 C UU
        U 0
        G FIN2:MAG G FIN2:$V(XDE)\16384'=1
        V XDE+2::0 I ID="" V XDE::$V(XDE)#16384+16384 G F1A
        V XDE::$V(XDE)#16384
F1A     W !,"DISK ",XD,XU,"  -- DISMOUNTED",!
FIN2    G FIN3:$V(MDE)\16384'=1
        V MDE+2::0 I ID="" V MDE::$V(MDE)#16384+16384 G F2A
        V MDE::$V(MDE)#16384
F2A     W !,"DISK ",MD,MU,"  -- DISMOUNTED",!
FIN3    U 0 C 63 B 1 B -2 Q
SETBF   D %DDU^DPBEGIN
        I $P(%D," ",13),$P(%D," ",13)<BFA S BFA=$P(%D," ",13)
        K %D Q
