RESTMAS Q  ;DSM11 UTILITIES; COPYRIGHT 1980 DEC
MASMOU  ;
        S %FAIL=0
        U 63:(2:1),0 D MNTIT^RESTDO G TERM:%FAIL
        G BABAK:'MAS G WRONG:ML'=M
        I ID="" S MS=6*256 V DE+2::$V(812,0),DE::$V(DE)+MS G LODB
        S TYP=MTYP
LODB    V DE+2::$V(812,0) S MMS=$V(DE)\256#64+$V($V(44)+86)
        F I=0:2:190 V I:MMS:$V(512+I,0)
        Q
BABAK   W !,"! MASTER LABEL EXPECTED !",!
        W "THIS DISK HAS BACKUP LABEL:  ",M,! G STOP
WRONG   W !,"! WRONG DISK MOUNTED.  MASTER LABEL EXPECTED WAS:  ",ML,!
        W "MASTER LABEL ON THIS DISK IS:  ",M,! G STOP
TERM    U 0 W !,"TERMINATED BY OPERATOR.",! G STOP
STOP    S %FAIL=1 Q
