RMAP    ;16-May-83 ;UTILITIES ;ROUTINE MAPPING ;CREATES A MAPPED ROUTINE SECTION ;JHM
        D:$D(^UTILITY("MENU",$J,"MENU")) PUSH^%MENU S ^UTILITY("MENU",$J,"MENU")="^%MENU(""SYS"",""SYSTEM DEFINITION"",""ROUTINE MAP
PING"")" D %STT^%MENU
        S %NOPAUSE=1 Q
