SGBUFF  ;3-May-83 ;UTILITIES ;SYSGEN ;GETS VALUES FOR BUFFER ALLOCATION ;JHM
        Q
START   W !,"PART 8:",?10,"MEMORY BUFFER ALLOCATION",!,"-------",!
        S EXECSIZ=KERSIZ+CCEND+63\64*64,MEMTOT=^SYS(ID,"MEMORY SIZE","K BYTES")*1024
        S PARMIN=^SYS(ID,"OPTIONS","JRNL")="Y"*1024+1024+8192
        S CCHMAX="",DMABUF=20*1024
        I MEMTOT<253953 S MEMLEFT=MEMTOT-EXECSIZ,MEMUSE=MEMTOT-MEMLEFT,PARDEF=PARMIN,RNGMAX=MEMTOT-PARMIN-DMABUF
        E  S MEMLEFT=253952-EXECSIZ,MEMUSE=EXECSIZ,PARDEF=0,RNGMAX=253952-DMABUF
        D SHOMEM
        I ^SYS(ID,"OPTIONS","DDP")="N" G CHKSIZ
DDPBUF  S DEF=^SYS(ID,"MEM.ALLOC","DDP BUFFERS")\512,QUES="DDPQ" X:EXTH ^%Q("EXTH")
        I SOFT S ANS=DEF W !,"Number of 512 byte DDP buffers:",?50,$J(ANS,6),! G CHKSIZ
        X ^%Q("SGEN") G:%A RETURN I ANS'?1N.N!(ANS>250) D IV G DDPBUF
        S ^SYS(ID,"MEM.ALLOC","DDP BUFFERS")=ANS*512
CHKSIZ  S POOL=^SYS(ID,"DMC","LINES")*36*64+^SYS(ID,"MEM.ALLOC","DDP BUFFERS")+^("DDP BASE TABLES")
        D CHKRNG G:%A RETURN
RINGBS  S DEF=64,QUES="RBS" X:EXTH ^%Q("EXTH")
        I SOFT S ANS=DEF W !,"Default terminal RING BUFFER size:",?50,$J(ANS,6)," Bytes",! G RBSET
        I $D(^SYS(ID,"MEM.ALLOC","RING BUFFERS","DEFAULT SIZE")) S DEF=^("DEFAULT SIZE")
        X ^%Q("SGEN") G:%A DDPBUF I ANS'?1N.N!(ANS<32)!(ANS>255) D IV G RINGBS
RBSET   S ^SYS(ID,"MEM.ALLOC","RING BUFFERS","DEFAULT SIZE")=ANS
RBUFWD  S (DEF,MIN)=^SYS(ID,"MEM.ALLOC","RING BUFFERS","DEFAULT SIZE")*2
        S TT="",DEF=0 F I=1:1 S TT=$O(^SYS(ID,"TTY",TT)) Q:TT=""  S DEF=DEF+MIN
        S DEF=^SYS(ID,"JOBCOM","CHANNELS")*^("RBSIZE")+DEF
        I $D(^SYS(ID,"MEM.ALLOC","RING BUFFERS","POOL")),'SOFT S DEF=^("POOL")
        S QUES="RBP" X:EXTH ^%Q("EXTH")
        I SOFT S ANS=DEF W !,"Total space allocated to RING BUFFERS:",?50,$J(ANS,6)," Bytes",! G SETRBP
        X ^%Q("SGEN") G:%A START I ANS'?1N.N!(ANS<MIN) D IV G RBUFWD
SETRBP  S POOL=ANS D MOD64^SGDATA,CHKRNG G:%A RBUFWD
        S ^SYS(ID,"MEM.ALLOC","RING BUFFERS","POOL")=POOL
CACHE   I MEMTOT<253953 S CCHMAX=MEMLEFT-PARMIN\1024,DEF=CCHMAX\2
        E  S CCHMAX=MEMTOT-MEMUSE-PARMIN\1024,DEF=CCHMAX\2 D
        .I CCHMAX'>$V(ST+430) Q
        .S CCHMAX=$V(ST+430)
        .I DEF\8>70 S DEF=MEMTOT-MEMUSE-PARMIN-(70*8192)\1024
        .I DEF>CCHMAX S DEF=CCHMAX
        D SHOMEM
        I $D(^SYS(ID,"MEM.ALLOC","DISK-TAPE BUFFER POOL")),^("DISK-TAPE BUFFER POOL")\1024'>CCHMAX,'SOFT S DEF=^("DISK-TAPE BUFFER POOL")\1024
        S MIN=^SYS(ID,"MEM.ALLOC","JOURNAL BUFFERS")+7 I DEF<MIN S DEF=MIN
        S QUES="CAS" X:EXTH ^%Q("EXTH")
        I SOFT S ANS=DEF W !,"Total number of 1 K byte DISK-TAPE cache buffers:",?50,$J(ANS,6),! G SETCAS
        X ^%Q("SGEN") G:%A START I ANS'?1N.N!(ANS<MIN) D IV G CACHE
SETCAS  S POOL=ANS*1024 D CHKCCH G:%A CACHE
        S ^SYS(ID,"MEM.ALLOC","DISK-TAPE BUFFER POOL")=POOL
DONE    K POOL,MIN S MEMUSE(18)=MEMUSE D START^SGDATA I %A G:'SOFT START
RETURN  Q
SHOMEM  Q:SOFT  W !,"Space remaining for Buffers and Partitions:",?50
        I MEMTOT<253952 W $J(MEMLEFT/1024,6,2)," K Bytes"
        E  W $J(MEMTOT-MEMUSE/1024,6,2)," K Bytes"
        I CCHMAX'="" W !,"Maximum space that can be used for Buffers:",?50,$J(CCHMAX,6,2)," K bytes",! Q
        W ! Q
        W ! Q
CHKCCH  I ANS>CCHMAX S %A=1,QUES="OVR18",SOFT=0 X ^%Q("QUERYH") Q
        G ADJMEM
CHKRNG  I MEMUSE+POOL>RNGMAX S %A=1,QUES="OVR18",SOFT=0 X ^%Q("QUERYH") Q
ROOM    I PARDEF>(MEMLEFT-POOL) S %A=1,QUES="OVRPAR",SOFT=0 X ^%Q("QUERYH") Q
ADJMEM  S MEMLEFT=MEMLEFT-POOL,MEMUSE=MEMUSE+POOL,%A=0 Q
IV      W !,"   Incorrect response - enter '?' for more information",! Q
DDPQH   ;
RBPH    ;
RBSH    ;
CASH    ;
OVR18H  ;
OVRPARH ;
HELP    S TAG=QUES_"H" D TEXT^SGBUFFH Q
DDPQ    ;;1;;8.1;;1
        ;;Enter the number of 512 byte DDP buffers
RBS     ;;1;;8.2;;1
        ;;Enter the default terminal RING BUFFER size
RBP     ;;1;;8.3;;1
        ;;Enter the number of bytes to allocate to RING BUFFER space
CAS     ;;1;;8.4;;1
        ;;Enter the number of DISK-TAPE cache blocks to allocate
