SYSDEF  ;13-May-83 ;UTILITIES ;SYSTEM MAINTENANCE ;MENU FOR SYSTEM DEFINITION ROUTINES ;JHM
SYS     ;
        D:$D(^UTILITY("MENU",$J,"MENU")) PUSH^%MENU S ^UTILITY("MENU",$J,"MENU")="^%MENU(""SYS"",""SYSTEM DEFINITION"")" D %STT^%MENU
        S %NOPAUSE=1 Q
