UCITRAN ;10-Jan-84 ;UTITLITIES ;UCI TRANSLATION MAINTENANCE ;MENU FOR UCI TRANSLATION OPTIONS ;JHM
SYSDEF  ;
SYS     ;
        D:$D(^UTILITY("MENU",$J,"MENU")) PUSH^%MENU S ^UTILITY("MENU",$J,"MENU")="^%MENU(""SYS"",""SYSTEM DEFINITION"",""UCI TRANSLATION"")" D %STT^%MENU
        S %NOPAUSE=1 Q
