V3UTILS ;13-May-83 ;UTILITIES ;INSTALLATION ;KIT MAP ;JBH
        Q
ROUGLO  U U F I=1:1 S P=$P($T(PROGS+I)," ",2) Q:P="UTILS"  X "ZL @P ZP"
        D TPMRK
        S COL=1
        F L=1:1 S P=$P($T(UTILS+L)," ",2) Q:P=";"  W P,! X "ZL @P ZP" U 0 W:COL=1 ! W ?COL,P S COL=COL+10#80 U U I SDP,$ZA>LAST D MO
UNT^MAKESDP
        D TPMRK I SDP W "START GLOBALS",!
        S PR=0 D PUTG^V3TAPEGL
        U U W "*TM*",! I SDP W "END OF GLOBALS",!
        D TPMRK,TPMRK
        Q
TPMRK   U U I 'SDP W *3 Q
        W "*TM*",! Q
PRUTIL  U 0 R "Print on device ? ",U O U
        U U F P=1:1 S PROG=$P($T(UTILS+P)," ",2) Q:PROG=""  X "ZL @PROG P  W #"
        D PRGLOB^V3TAPEGL Q
PROGS   ;
        INSTALL
        DPBEGIN
        DPFORMAT
        DPFMT30
        DPTEST
        DPLABGET
        DPBBSET
        BBTAB
        LABEL
        DPNEWL
        DPINIT
        DPUTILOD
        DPSYCOPY
        STUDIST
UTILS   UTILS
        %BLKWT
        %BN
        %CRF
        %CRF1
        %CURSOR
        %D
        %DH
        %DIAL
        %DO
        %DOC
        %E
        %EB
        %ED
        %EDI
        %EDIEDT
        %EDIFIL
        %EDIINS
        %EDILST
        %EDIMAC
        %EGD
        %ER
        %ET
        %FGC
        %FGR
        %FGR1
        %FGR2
        %FGR3
        %FGR4
        %FGT
        %FL
        %G
        %G1
        %G2
        %G3
        %G4
        %GCH
        %GD
        %GE
        %GEDIT
        %GGP
        %GL
        %GL1
        %GLO1
        %GLO2
        %GLOMAN
        %GR
        %GRT
        %GRTINI
        %GRTR
        %GRTS
        %GS
        %GS1
        %GSEL
        %GSEL1
        %GTI
        %GTO
        %GUCI
        %H
        %HD
        %HDR
        %HDR1
        %HELP
        %HELPED
        %HELPH
        %HELPMEN
        %IOS
        %IOS1
        %JOB
        %LIB
        %LNKMP
        %MENLIS
        %MENU
        %MTCHK
        %NAKED
        %OD
        %OVR
        %P
        %PC
        %PCMP
        %PCOMP
        %PCOPY
        %PCR
        %PD
        %PDEL
        %PEXC
        %PFL
        %PL
        %PP
        %PR
        %PRIO
        %PS
        %PSD
        %PSE
        %PSEDIT
        %PSEL
        %PXR
        %RCE
        %RCMP
        %RCOPY
        %RD
        %RDX
        %RM
        %RM1
        %RML
        %RR
        %RS
        %RSE
        %RSEL
        %STRTAB
        %SUM
        %SUM1
        %SUM2
        %SUM3
        %SUM4
        %SUM5
        %SUMSEL
        %SY
        %SYR
        %SYSROU
        %T
        %TDN
        %UTL
        %VAR
        %WU
        ACTJOB
        ALLOCAT
        ATTACH
        AUPAT
        AUPAT0
        AUPAT1
        AUPAT2
        BACKCRE
        BACKCRF
        BACKCRG
        BACKFL
        BACKHELA
        BACKHELP
        BACKJRN
        BACKLOGO
        BACKMGA
        BACKMM
        BACKMMGO
        BACKMNT
        BACKONE
        BACKPRT
        BACKSET
        BACKSTR
        BACKUNJR
        BACKUP
        BACKUPDO
        BACKUPPR
        BACKVARS
        BACKVERI
        BACKVRS2
        BBTAB
        BCS
        BLDMP
        BLDMP1
        BOOTCOPY
        BSC
        BSCBIT
        BSCEBC
        BSCHLT
        BSCMON
        BSCPE
        BSCPEB
        BSCPER
        BSCQUE
        BSCRCV
        BSCSTA
        BSCSTR
        BSCXMT
        CARE
        CONFIG
        CREATPQ
        CTK
        CTK0
        CTK1
        CTK2
        CTKDAT
        CTKUTL
        DAT
        DBT
        DBTALLY
        DDP
        DDPCIR
        DDPCON
        DDPLNK
        DDPSRV
        DDPUTL
        DDR
        DEJRNL
        DEJRNL1
        DEJRNL2
        DESPOOL
        DETACH
        DGAM
        DISKMAP
        DISKPREP
        DISKSIZ
        DISMOUNT
        DPBBSET
        DPBEGIN
        DPFMT30
        DPFORMAT
        DPINIT
        DPLABGET
        DPNEWL
        DPSYCOPY
        DPTEST
        DPUTILOD
        DSKTRACK
        FASTDBT
        FASTGTO
        FASTIC
        FIX
        FIXDATA
        FIXDATA1
        FIXGD
        FIXMAP
        FIXMAP1
        FIXPTR
        FIXPTR1
        FIXROU
        GC
        GC1
        GLBPLACE
        IC
        IC0
        IC1
        IC2
        IC3
        IC4
        INSTALL
        JOBTAB
        JRNALL
        JRNCOPY
        JRNCOPY1
        JRNCOPY4
        JRNDEALL
        JRNDKEND
        JRNGETST
        JRNINIT
        JRNL
        JRNLSHOW
        JRNRECOV
        JRNSTART
        JRNSTOP
        JRNSTU
        KTR
        KTR1
        KTRUDA
        LABEL
        LABELMT
        LABSHO
        LMAP
        LOAD
        LOADR
        LOCKTAB
        MAKESDP
        MAPMOUNT
        MAPM1
        MBP
        MBP1
        MBP1H
        MBP2
        MBPH
        MDAT
        MMD
        MOUNT
        MOUNTX
        MSUROU
        MUX
        MUX1
        MUXDEF
        PARTAB
        PARVEC
        PARVEC0
        PATCH
        PATFL1
        PATFL2
        PATFL3
        PATFL4
        PATFL5
        PCHIST
        PCHIST1
        PCHISTP
        PEEK
        REPTAB
        REST
        RESTDO
        RESTDOMG
        RESTMAGU
        RESTMAS
        RESTMNT
        RESTRESB
        RESTRTNS
        RJD
        RMAP
        RMBLD
        RMDIS
        RMSHO
        RMLOAD
        RTHELP
        RTHIST
        RTHIST1
        RTHISTP
        SAVBOOMK
        SAVBOOT
        SDCCOPY
        SDP
        SETHOST
        SGAUTO
        SGBUFF
        SGBUFFH
        SGDATA
        SGDEVS
        SGDISK
        SGDMC
        SGLOAD
        SGMAGT
        SGMEM
        SGOPTH
        SGOPTS
        SGPART
        SGSOFT
        SGSUB
        SPL
        SPLALL
        SPLINI
        SPLREM
        SPLSTR
        SSD
        STA
        STU
        STU1
        STU2
        STU3
        STU4
        STUBLD
        STUBLD2
        STUBLDH
        STUCSR
        STUDIST
        STUSETPV
        STUSPL
        SWREG
        SYCOPY
        SYS
        SYSDEF
        SYSGEN
        SYSROU
        SYSTAB
        SYSTAB0
        SYSTAB1
        SYSTAB15
        SYSTAB2
        SYSWAIT
        SYTOTAPE
        TAPCOPA
        TAPECOPY
        TIM
        TRANTAB
        TRANTB1
        TTTG
        TTTSHO
        UCIADD
        UCIEDIT
        UCILI
        UCITAB
        UCITRAN
        UNLOAD
        UTL
        V3TAPEGL
        V3UTILS
        VER
UTILEND ;
