LOADR   ;14-Dec-81 ;UTILITY ;LOADABLE DRIVER ;LOADS A DRIVER ;JHM
        Q
STU     S DRV=""
STU2    S DRV=$O(^SYS(0,"STARTUP","DRIVER",DRV)) G CLEANUP:DRV="",STU2:^(DRV)="N"
        I ^SYS(ID,"DRIVERS",DRV)="N" W !,DRV," driver not configured during SYSGEN, unable to load" G STU2
        D GETDEF W !,"Loading ",DRV," driver..." D INIT,FINDR G STU2:CON=0 D LOAD G STU2
INIT    S ST=$V(44),DEVTAB=$V(ST+8),USRMM=$V(ST+146),INBLK=0
        C 63 O 63 U 63:(::"Z"),0 V 0:"S0" S ANSTRT=$V(497,0)*65536+$V(498,0)
        U 63:(::"C"),0 V 2:"S0" S ONDSK=0 F I=132:2:148 S ONDSK=$V(ST+I,0)*64+ONDSK
        K DRVLST S DRVLST=$P($T(DRVTAB),";;",2)
        F %I=1:1:+DRVLST S DRVLST=DRVLST_";"_$P($T(DRVTAB+%I)," ")
        F %I=1:1:$P($T(CONTAB),";;",2) S DRVLST(%I)=$P($T(CONTAB+%I),";;",2,4)
        Q
FINDR   S ADR=ST+152 D GETWORD S ADR=CON-32768+ONDSK
        I DRV?1N.N F %I=1:1:DRV D GETWORD S DRVBEG=ADR,ADR=ADR+CON G FDON:'CON
        I DRV?1U.E S DRVCD=$P($T(@DRV),";;",2) F %I=1:1 D GETWORD G FDON:'CON S DRVBEG=ADR,ADR=ADR+2,C=CON D GETWORD Q:$C(CON#256)_$
C(CON\256)=DRVCD  S ADR=ADR-2+C
        S ADR=DRVBEG D GETWORD S DRVLN=CON
        S ADR=DRVBEG+5 D GETWORD S DDBSIZ=CON
        S ADR=DRVBEG+2 D GETWORD S CON=$C(CON#256)_$C(CON\256)
FDON    Q
LOAD    S DDB=0 F %I=1:1:DEV F %J=1:1:+DEV(%I) S DDB=DDB+1,DEVAS=$P(DEV(%I),",",4) I $V($P(DEVAS," ",%J)+DEVTAB)#256'=255 G NODEV
        S HOLE=$V(128,USRMM)
        S HDRSIZ=22
        S CODSIZ=DRVLN-HDRSIZ-DDBSIZ
        S DRVLN=DDB-1*DDBSIZ+DRVLN
        F %I=0:0 G NOSPC:'$V(HOLE,USRMM) Q:($V(HOLE,USRMM)'<DRVLN&'$V(HOLE+2,USRMM))  S HOLE=HOLE+$V(HOLE,USRMM)
        S IMSIZ=CODSIZ+HDRSIZ+DDBSIZ\1024+3
        C 63 O 63:IMSIZ:1 E  G NOVW
        S SPCSIZ=$V(HOLE,USRMM),ADR=DRVBEG,VWOFS=ADR#1024
        S INBLK=ADR\1024+2 F I=INBLK:1:IMSIZ+INBLK-1 U 63:(I-INBLK+1:1),0 S BLK=$S(I>91:I-92+ANSTRT,1:I) V BLK:"S0"
        U 63:(1:IMSIZ),0 V HOLE:USRMM:VWOFS:0:HDRSIZ S OFS=HDRSIZ
        S DDBBEG=HDRSIZ F %I=1:1:DDB V HOLE+OFS:USRMM:DDBBEG+VWOFS:0:DDBSIZ S OFS=OFS+DDBSIZ
        S RELOFS=HOLE+OFS
        V HOLE+OFS:USRMM:VWOFS+DDBBEG+DDBSIZ:0:CODSIZ
        S OFS=OFS+CODSIZ
BLDHD   V HOLE:USRMM:DRVLN S LFTOVR=SPCSIZ-DRVLN
        I LFTOVR<10 G CONNCT:'LFTOVR V HOLE:USRMM:SPCSIZ
        E  V HOLE+OFS:USRMM:LFTOVR,HOLE+OFS+2:USRMM:0
CONNCT  S DDB=0
        F CNTRL=1:1:DEV S %OD=$P(DEV(CNTRL),",",2) D %OD S CSR=%OD,%OD=$P(DEV(CNTRL),",",3) D %OD S DEVAS=$P(DEV(CNTRL),",",4) D
        .F UNI=1:1:+DEV(CNTRL) S DDB=DDB+1,DEVNUM=$P(DEVAS," ",UNI),DDBSTR=DDB-1*DDBSIZ+HOLE+22 D FIXDSP,SETVEC,ENBDEV,MRKDEV
        V HOLE+4:USRMM:$V(HOLE+4,USRMM)+DDB
        W " loaded and accessible via device" W:DDB-1 "s" F %I=1:1:DEV W " ",$P(DEV(%I),",",4)
        Q
GETWORD I ADR\1024+2'=INBLK S INBLK=ADR\1024+2,BLK=$S(INBLK>91:INBLK-92+ANSTRT,1:INBLK) V BLK:"S0"
        S CON=$V(ADR#1024,0) Q
GETDEF  K DEV S DEV=^SYS(ID,"DRIVERS",DRV,"CONTROLLER")
        F %I=1:1:DEV S DEV(%I)=^SYS(ID,"DRIVERS",DRV,"UNITS") D
        .S CONT=^SYS(ID,"DRIVERS",DRV,"CONTROLLER",%I,"TYPE"),NUM=^("NUMBER"),DEVNUM=^("DEVICES")
        .S DEV(%I)=DEV(%I)_","_^SYS(ID,"CONTROLLER",CONT,NUM,"CSR")_","_^("VECTOR")_","_DEVNUM_","_CONT
        Q
FIXDSP  S DSPOFS=DEVNUM-51*16 V DSPOFS+14:USRMM:DDBSTR+4+32768
        F %I=0:2:12 V DSPOFS+%I:USRMM:$V(HOLE+6+%I,USRMM)+RELOFS+32768
        Q
SETVEC  V DDBSTR+2:USRMM:$V(HOLE+20,USRMM)+RELOFS+32768
        V DDBSTR+4:USRMM:CSR,DDBSTR+6:USRMM:%OD
        V DDBSTR+8:USRMM:CNTRL-1*256+DEVNUM-51,DDBSTR+10:USRMM:$V(DDBSTR+10,USRMM)+UNI-$S($P(DEV(CNTRL),",",5)="DPV11":0,1:1) Q
ENBDEV  I DEVNUM#2 V DEVTAB+DEVNUM-1::$V(DEVTAB+DEVNUM-1)#256
        E  V DEVTAB+DEVNUM::$V(DEVTAB+DEVNUM+1)*256
        Q
MRKDEV  S ^SYS(0,"LOADED DRIVERS",DEVNUM)=DRV Q
NODEV   W !,"Device ",$P(DEVAS," ",%J)," is already assigned," G NOLOAD
NOVW    W !,"View buffer device 63 not available," G NOLOAD
NOSPC   W !,"Memory space not available"
NOLOAD  W "  ",DRV," driver not loaded",!
CLEANUP K UNI,DEVNUM,DEVTAB,VEC,CSR,MEM,HOLE,%DO,%OD,ADR,DRVLN,KERBAS,LDOFF,LFTOVR,SPCSIZ,WORD,DEVAS,DEV,CON,DDBSIZ,OFS,RELOFS,USRAD
R,INBLK,DDBSTR,CNTRL,DDB
        Q
%OD     S %B=0 F %I=1:1:$L(%OD) S %B=%B*8+$E(%OD,%I)
        S %OD=%B K %I,%B Q
DRVTAB  ;;3
TU58    ;;DD
RX02    ;;DY
BISYNC  ;;XJ
CONTAB  ;;5
        ;;DUP11;;BISYNC;;1
        ;;DUV11;;BISYNC;;1
        ;;DPV11;;BISYNC;;1
        ;;RX02;;RX02;;2
        ;;TU58;;TU58;;2
