MUX     ;RLW,DMW SET UP DDB PARAMETERS (CALLED BY ^SG4)
        D ID^SYSROU Q:ID="^"  D SYSGEN,^MDAT Q
SYSGEN  U 0 W !!,"****** Terminal device characteristics ******"
        W !!,"Enter device number, or range of device numbers (NN:NN). Enter <CR> when done."
        D HDR^MUX1
DEV     D DEV^MUX1 I DEV=""!(DEV="^") K (SGN,ID,DMB) Q
        I RANGE="Y" S RAN=DEV,DEV=START W !,DEV
        D DEF^MUXDEF I DEV<20 S PAR="NONE" G CRT:'LP S OP="Y",(RTN,STALL)=0,(PAR,CRT,DATA,LOGIN,TAB,AUT,ZUSE)="N" G LOWER
PAR     R ?7,PAR G:PAR="^" DEV I '(PAR=""!(PAR="E")!(PAR="O")!(PAR="N")) D IV2^MUX1 G PAR
        W:PAR="" $E(PARDF,1) S:PAR="" PAR=PARDF S:PAR="E" PAR="EVEN" S:PAR="O" PAR="ODD" S:PAR="N" PAR="NONE"
CRT     R ?10,CRT W:CRT="" CRTDF S:CRT="" CRT=CRTDF G:CRT="^" DEV I "YN"'[CRT D IV1^MUX1 G CRT
AUTO    I DEV<20 S AUT="N" G DATA
        R ?13,AUT W:AUT="" AUTDF S:AUT="" AUT=AUTDF G:AUT="^" DEV I "YN"'[AUT D IV1^MUX1 G AUTO
        I $E(AUT)="Y" S (RCVR,XMIT)=4800 W ?15,RCVR,?20,XMIT G DATA
RCVR    R ?15,RCVR G:RCVR="^" DEV I RCVR="" S RCVR=RCVRDF W RCVR G XMIT
        I CNT["DZ",'$F($T(BAUD),","_RCVR_",") D IV3^MUX1 G RCVR
        I CNT="DH11",'$F($T(BAUD1),","_RCVR_",") D IV3^MUX1 G RCVR
        I CNT["DHV"!(CNT["DHU"),'$F($T(BAUD2),","_RCVR_",") D IV3^MUX1 G RCVR
XMIT    I CNT["DZ" S XMIT=RCVR W ?20,XMIT G DATA
        R ?20,XMIT G:XMIT="^" DEV I XMIT="" S XMIT=XMITDF W XMIT
        I CNT="DH11",'$F($T(BAUD1),","_XMIT_",") D IV3^MUX1 G XMIT
        I CNT["DHV"!(CNT["DHU"),'$F($T(BAUD2),","_XMIT_",") D IV3^MUX1 G XMIT
DATA    I ^SYS(ID,"OPTIONS","MODEM")="N"!(DEV=1) S DATA="N" W ?25,DATA G ZUSE
        R ?25,DATA G:DATA="^" DEV W:DATA="" DATADF S:DATA="" DATA=DATADF I "YN"'[DATA D IV1^MUX1 G DATA
ZUSE    R ?28,ZUSE W:ZUSE="" ZUSEDF G:ZUSE="^" DEV S:ZUSE="" ZUSE=ZUSEDF I "YN"'[ZUSE D IV1^MUX1 G ZUSE
OP      I DEV=1 S OP="N" W ?32,OP G LOGIN
        R ?32,OP G:OP="^" DEV W:OP="" OPDF S:OP="" OP=OPDF I "YN"'[OP D IV1^MUX1 G OP
LOGIN   I DEV=1 S LOGIN=LOGDF W ?36,LOGIN G STALL
        I OP="Y" S LOGIN="N" W ?36,LOGIN G STALL
        R ?36,LOGIN G:LOGIN="^" DEV W:LOGIN="" LOGDF S:LOGIN="" LOGIN=LOGDF I "YN"'[LOGIN D IV1^MUX1 G LOGIN
STALL   R ?40,STALL G:STALL="^" DEV W:STALL="" STALDF S:STALL="" STALL=STALDF I STALL'=+STALL!(STALL<0)!(STALL>15) D IV6^MUX1 G STAL
L
TAB     R ?43,TAB G:TAB="^" DEV W:TAB="" TABDF S:TAB="" TAB=TABDF I "YN"'[TAB D IV1^MUX1 G TAB
LOWER   R ?46,LOWER G:LOWER="^" DEV W:LOWER="" LOWDF S:LOWER="" LOWER=LOWDF I "YN"'[LOWER D IV1^MUX1 G LOWER
MAR     R ?50,MAR W:MAR="" MARDF S:MAR="" MAR=MARDF G:MAR="^" DEV I MAR<0!(MAR>255)!(MAR'=+MAR) D IV4^MUX1 G MAR
        I LP G CMNT
RTN     I OP="Y" S RTN=0 W ?56,RTN G CMNT
        R ?56,RTN G:RTN="^" DEV W:RTN="" RTNDF S:RTN="" RTN=RTNDF I RTN<0!(RTN>7)!(RTN'=+RTN) D IV5^MUX1 G RTN
CMNT    R ?62,CMNT G:CMNT="^" DEV W:CMNT="" "N" S:CMNT="" CMNT="N" I CMNT'="Y"&(CMNT'="N") D IV7^MUX1 G CMNT
        I CMNT="Y" W !,"Comment <",^SYS(ID,"TTY",DEV,"COMMENT") R "> ",COM G CMNT:COM="^" W:COM="" ^("COMMENT") S:COM="" COM=^("COMM
ENT") S:COM="-" COM="" S ^("COMMENT")=COM
        W *13
DONE    I RANGE="Y" G RANGE
SET     D DEFINE^MUXDEF
CONT    I DMB'="D" S LINE=DEV D SETMEM
        G DEV
RANGE   S LINE=DEV F DEV=DEV:1:END D DEFINE^MUXDEF
        I DMB'="D" F LINE=LINE:1:END D SETMEM
        G DEV
SETMEM  V ST::64 S DEVTAB=$V(ST+8),US=$V(DEVTAB+LINE)#256
        I US=0 G SETMEM1
        I $J*2=US,^SYS(ID,"TTY",LINE,"AUTOBAUD")="N",^("OUTPUT ONLY")="N" G SETMEM1
        V ST::0 W !,"Can't make memory changes for device ",LINE,", because it is in use." Q
SETMEM1 C:US LINE D SETDDB^STU3 ZU LINE:(:::::::DDBLPR)
        I CONT["DH" S $ZT="SETMEM2" O LINE::0 C LINE
        O:US LINE
SETMEM2 U 0 V ST::0 Q
BAUD2   ;;75,110,134.5,150,300,600,1200,1800,2000,2400,4800,9600,19200,
BAUD1   ;;0,50,75,110,134.5,150,200,300,600,1200,1800,2400,4800,9600,
BAUD    ;;50,75,110,134.5,150,300,600,1200,1800,2000,2400,3600,4800,7200,9600,
