STU3    Q  ;[JBH 20JAN80 DEC COPYRIGHT 1980] START UP TERMINALS
SETDDB  D %ODSET
SETDDB1 I LINE<64 S DDB=$V($V(44)+10)+(LINE-1*($V($V(44)+68))) G INIT
        S DDB=$V($V(44)+20)+(LINE-64*$V($V(44)+68))
INIT    S CONT=^SYS(ID,"TTY",LINE,"CONTROLLER"),DMC=0,LPT=0,DDBMDM=0,DDBLPR=0,INHIB=192
        I CONT="DMC11" S DMC=1 G SETSIN
        I CONT="LP11" S LPT=1 G SETSIN
        I CONT="DL11"!(CONT="CONSOLE DL") G SETSIN
        I '$F("DH11DZ11DZV11DHU11DHV11",CONT) U 0 W !,"Unknown controller specified for line ",LINE,! Q
        S DDBLPR=^SYS(ID,"TTY",LINE,"LPR")
        I CONT'="DH11" G @("SET"_$E(CONT,1,$F(CONT,"1")-2))
        S MUX=LINE-64\16
        S DDBDEV=32+(LINE#16) I ^SYS(ID,"CONTROLLER","DH11",MUX,"MODEM CONTROL")'="Y" S MDMVEC="" G SETDH
        S %OD=^("MODEM CONTROL","CSR") D %OD S DDBMDM=%OD,%OD=^("VECTOR") D %OD S MDMVEC=%OD
SETDH   S %OD=^SYS(ID,"CONTROLLER","DH11",MUX,"CSR"),MUXSIZ=16 D %OD S DDBCSR=%OD D SETDEV I LINE#16'=0 Q
        I MDMVEC V MDMVEC::DDB,MDMVEC+2::INHIB+1
SETVC1  S %OD=^SYS(ID,"CONTROLLER",CONT,MUX,"VECTOR") D %OD S VEC=%OD V VEC::DDB,VEC+2::INHIB,VEC+4::DDB,VEC+6::INHIB+2
        Q
SETDHU  S MUX=(LINE-64-(^SYS(ID,"CONTROLLER","DH11")*16))\16,MUXSIZ=16
        S %OD=^SYS(ID,"CONTROLLER","DHU11",MUX,"CSR") D %OD S DDBCSR=%OD,DDBDEV=48+(LINE#16)
        D SETDEV Q:LINE#16  G SETVC1
SETDZ   S MUX=(LINE-64-(^SYS(ID,"CONTROLLER","DHU11")*16))-(^("DH11")*16)\8,MUXSIZ=8
        S %OD=^SYS(ID,"CONTROLLER","DZ11",MUX,"CSR") D %OD S DDBCSR=%OD,DDBDEV=16+(LINE#8)
        I $D(DZDDB) S:'DZDDB DZDDB=DDB+4 I DZDDB>DDB S DZDDB=DDB+4
        D SETDEV Q:LINE#8  G SETVC1
SETDHV  S MUX=LINE-64\8,%OD=^SYS(ID,"CONTROLLER","DHV11",MUX,"CSR"),MUXSIZ=8
        D %OD S DDBCSR=%OD,DDBDEV=48+(LINE#8)
        D SETDEV Q:LINE#8  G SETVC1
SETDZV  S MUX=(LINE-64-(^SYS(ID,"CONTROLLER","DHV11")*8))\4,%OD=^SYS(ID,"CONTROLLER","DZV11",MUX,"CSR"),MUXSIZ=4
        D %OD S DDBCSR=%OD,DDBDEV=16+(LINE#4)
        I $D(DZDDB) S:'DZDDB DZDDB=DDB+4 I DZDDB>DDB S DZDDB=DDB+4
        D SETDEV Q:LINE#4  G SETVC1
SETSIN  S MDM=(^SYS(ID,"TTY",LINE,"MODEM CONTROL")="Y"),NO=^("CONTROLLER NUMBER"),%OD=^SYS(ID,"CONTROLLER",CONT,NO,"CSR"),MUXSIZ=0
        D %OD S DDBCSR=%OD,DDBDEV=0,%OD=^("VECTOR") D %OD S VEC=%OD V VEC::DDB,VEC+2::INHIB+MDM I LPT S DDBCSR=DDBCSR-4 G SETDEV
        V VEC+4::DDB,VEC+6::INHIB+DMC
        I DMC S PRMRY=^("PRIMARY"),DUP=^("HALF DUPLEX")
SETDEV  I '$D(MUXSIZ) S MUXSIZ=0
        V DDB::$V($V($V(44)+10)),DDB+2::$V($V($V(44)+10)+2),DDB+4::DDBCSR
        V DDB+6::^SYS(ID,"TTY",LINE,"STALL COUNT")#16*256+16384+(128*(^("PARITY")="EVEN"))+DDBDEV,DDB+8::0
        V DDB+10::256*^("ROUTINE")+^("OUTPUT MARGIN"),DDB+12::0
        V DDB+14::2*(^("OUTPUT ONLY")="Y")+(4*(^("CRT")="Y"))+(8*(^("MODEM CONTROL")="Y"))+(256*(^("LOGIN")="N"))+(1024*LPT)+(4096*(
^("TAB CONTROL")="Y"))+(16384*(^("LOWER CASE")'="Y"))
        V DDB+16::$V($V(44)+400),DDB+18::0,DDB+20::$V($V(44)+400),DDB+22::0,DDB+24::0
        V DDB+26::DDBMDM,DDB+28::DDBLPR,DDB+30::LINE,DDB+32::MUXSIZ*256+10,DDB+34::(^("AUTOBAUD")="Y"*2)+(^("ZUSE")'="Y"*256)
        V DDB+36::0,DDB+38::8192,DDB+40::2048,DDB+42::0,DDB+44::0 S DEVTAB=$V($V(44)+8)
        I DMC V DDB+2::$V($V(44)+392),DDB+6::DMCBUF,DDB+8::PRMRY="N"*2+(DUP="Y")*1024,DDB+14::8192 S DMCBUF=DMCBUF+36
        S TEMP=$V(DEVTAB+(LINE\2*2)) I LINE#2=1 S TEMP=TEMP#256 G DEVTAB
        S TEMP=TEMP\256*256
DEVTAB  I $V(DEVTAB+LINE)#256=255 V DEVTAB+(LINE\2*2)::TEMP
        Q
START   S ID=^SYS("0","RUNNING") W !!,"Building terminal control blocks...",! D %ODSET
        S LINE=1 C 1 D SETDDB1 O 1
        S DDB=$V(ST+10)+$V(ST+68) F I=0:2:$V(ST+68)-2 V DDB+I::0
        S DMCBUF=$V(ST+396) F LINE=3:1:^SYS(ID,"CONTROLLER","SINGLE")+2 D SETDDB1
        S SINGLE=LINE,LINE=64
        F MUX=0:1:^SYS(ID,"CONTROLLER","DH11")-1 F CHAN=1:1:16 D SETDDB1 S LINE=LINE+1
        F MUX=0:1:^SYS(ID,"CONTROLLER","DHU11")-1 F CHAN=1:1:16 D SETDDB1 S LINE=LINE+1
        F MUX=0:1:^SYS(ID,"CONTROLLER","DHV11")-1 F CHAN=1:1:8 D SETDDB1 S LINE=LINE+1
        S DZDDB=0 F MUX=0:1:^SYS(ID,"CONTROLLER","DZ11")-1 F CHAN=1:1:8 D SETDDB1 S LINE=LINE+1
        F MUX=0:1:^SYS(ID,"CONTROLLER","DZV11")-1 F CHAN=1:1:4 D SETDDB1 S LINE=LINE+1
        V ST+390::DZDDB
        S J=$V(ST+460) F I=192:2:LINE V J+I::$V(J+64),$V(ST+8)+I::0
        V ST+462::$V(ST+463)*256+$S(LINE=64:SINGLE,1:LINE-1)
        G START^STU4
%ODSET  S %B(1)=1 F %II=2:1:8 S %B(%II)=%B(%II-1)*8
        Q
%OD     S %B=0 F %II=1:1:$L(%OD) S %B=%B+($E(%OD,$L(%OD)+1-%II)*%B(%II))
        S %OD=%B Q
